### ISSUE TITLE
Debugging and getting intermediate result and metadata

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#100]
A big topic during the hackathon was debugging of our process graphs and getting information of intermediate result and other meta data. For example, after a filter one might want to know what data is left. GEE allows to add print() calls to get information about a variable with results between different steps. How could something like that be made available in openEO?
Related to https://github.com/Open-EO/openeo-python-client/issues/24

**Comment by m-mohr** [comment]
One idea would be to define some processes like print/debug/get_information/... that simply passes through the data (input = output), but sends the requested (debugging) information to the subscriptions, maybe in a separate "channel".

**Comment by edzer** [comment]
Couldn't this be (optional) under /job/status, like /job/job_id/status/logs or so?

When in synchronous mode, you'd probably expect that this is printed to your screen?

**Comment by m-mohr** [comment]
@edzer 
I think it could be part of the subscriptions API as described above for batch jobs. Then you get the information just-in-time and don't need to request the status over and over again. It would exclude synchronous calls though and web services (on demand processing) is also to be considered. 

In synchronous mode, how would you print it to screen? It needs to be transferred via HTTP to the user, but the result is already in the body so there is no good way to transfer this data over to the client. You could send some kind of multipart response, similar to file uploads in browsers, but this would make the endpoint overly complex compared to how simple its response is now.

We (Hackathon participants) haven't found a solution yet and there's probably no simple solution for it. That needs some more serious thoughts.

**Comment by m-mohr** [comment]
We have a draft for this using the Subscriptions API. The topic `openeo.output` can be used to send intermediate results and metadata and the topic `openeo.debug` can be used for debugging purposes.
