### ISSUE TITLE
Does downloading job results incur a fee?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#104]
Currently, people are billed by processing costs. Is there anybody who thinks downloading of processed results (and user files?) should be billed, too? If so, we would need to add it, too. This may be of special interest when sharing resources publicly becomes a thing with #85.

**Comment by mkadunc** [comment]
I think we need to add the option to include billing in download services as well, for at least two reasons:
- in case of on-the-fly processing, request for download triggers processing, so the download and processing action are conflated into a single thing from the user's perspective
- as you note, if sharing processed result is a use case we want to support (not sure we do), download requests could take up a large portion of the back-end resources; from our experience the cost of data transfer from cloud out into the internet is substantial, on a par with processing costs (AWS EC2 is ~$0.05 per CPU hour, $0.09 per 1GB output traffic)

**Comment by m-mohr** [comment]
@mkadunc Who would be paying for downloading? The user who has generated the results or the one who is downloading the results?

**Comment by m-mohr** [comment]
So, I'll propose this model for downloading:

* Downloading synchronously processed data (`POST /preview`) is always included in the `OpenEO-Costs` header returned. Preview is only used by the owner and can't be shared so there is no problem with "requester pays".
* The estimates for batch jobs (`GET /jobs/:job_id/estimate`) gets a new property `downloads_included` which specifies how many full downloads of the processed data are included in the estimate. (`GET /jobs/:job_id/results`) has a new header that indicates the costs for downloading. If a requester other than the owner is requesting the data of a shared job this header indicates the costs for the requester.
* Shared web services are usually paid by the owner, but this highly depends on the web service type and whether it supports to charge fees or not.
