### ISSUE TITLE
Change the definition of a process_graph

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#107]
Issues such as #89 or #106 require a change in the process graph definition as objects are required to/should be used.

Values of a process argument are defined as follows:
`<Value> := <string|number|array|boolean|null|Process>`
Source: https://open-eo.github.io/openeo-api/v/0.3.0/processgraphs/index.html

For the mentioned issues (and probably others) we probably need to change the definition of values to:
`<Value> := <string|number|array|boolean|null|object|Process>`

@flahn Does this make things much more complicated for you? I remember that you voted to not allow objects in process graphs as argument values.

**Comment by flahn** [comment]
Not that complicated. When we have a fixed identifier key (like process_id) to identify the process, then it is fine with me.

**Comment by m-mohr** [comment]
Implemented with the referenced commits.
