### ISSUE TITLE
Distinction between raster and vector formats

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-api#108]
Currently we provide an endpoint to list all available data formats (`/output_formats`). From a clients perspective I think it would be a good idea to state if a format can be used for raster, for vector data or for both (e.g. GeoPackage). It will help to prevent errors in the client even before the processing has been started.

**Comment by m-mohr** [comment]
How should we define that? Something like this?
```
{
  "default": "GTiff",
  "formats": {
    "GTiff": {
      "parameters": {},
      "raster": true
    },
    "PNG": {
      "parameters": {},
      "raster": true
      }
    },
    "JSON": {
      "vector": true
    },
    "GeoPackage": {
      "raster": true,
      "vector": true
    },
  }
}
```
Should there be a default for both vector and raster? Currently we just have one default format.

**Comment by m-mohr** [comment]
After a long discussion we decided to go the route proposed in #108.
