### ISSUE TITLE
Pilot users / implementations

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#109]
During the Hackathon and review meeting, there was the idea to have a list of new functionality and which partner is responsible for implementing and testing it practically. That ensures everything new is practically tested and we have opinions for the next version. Ideally, it shouldn't be the person suggesting it. There should be two back-ends/clients implementing it for broader feedback. ;-)

Here is a list of topics, please comment below and I'll add you here:

| Feature                              | Pilot user (back-end) | Pilot user (client) |
| ------------------------------------ | --------------------- | ------------------- |
| Capabilities                         | *All*                 | *All*               |
| EO Data discovery                    | EURAC / EODC / GEE    | *All*               |
| Process discovery                    | *All*                 | *All*               |
| OpenID Connect                       | EODC                  | R                   |
| UDFs                                 | R / VITO / mundialis  | Python / R          |
| Billing (across all endpoints)       | ?                     | JavaScript          |
| Subscription API                     | GEE                   | JavaScript          |
| File management                      | R, GEE                | *All*               |
| Process graph management             | R, GEE                | *All*               |
| Validate process graphs              | R, GEE                 | R                   |
| Process graph variables              | GEE                     | JavaScript           |
| Previews (sync. jobs)              | GEE, EURAC, VITO           | JavaScript           |
| Create web services from batch job results | EURAC                     | JavaScript           |
| Loading stored (external) process graphs      | GEE                     | Python              |
| Full batch job processing workflow   | VITO, EURAC                  | *All*               |
| Downloading job results              | VITO, EURAC                  | *All*               |
| Secondary web services (WMS)         | R                     | JavaScript          |
| Secondary web services (WMTS)        | VITO                  | Python              |
| Secondary web services (TMS)         | VITO                  | Python              |
| Secondary web services (XYZ)         | GEE                   | JavaScript          |

**Comment by m-mohr** [comment]
@bgoesswe I added the Python client to "Loading external process graphs". We'll see who implements it server-side.

**Comment by jdries** [comment]
The Geopyspark backend will try to implements:

- full batch processing (mostly done, needs testing)
- downloading job results
- TMS service (works, although not very fast, but TMS does not support time dimension)
- WMTS service (similar to TMS, but supports time dimension)

The Python client will also support creating a WMTS/TMS service.

**Comment by m-mohr** [comment]
@jdries Thank you, has been added to the list.

**Comment by m-mohr** [comment]
> I am interested in "Loading external process graphs" with python client, but not sure, which back end would like to support it.

@bgoesswe GEE will support it. I'll let you know once it is implemented.

**Comment by m-mohr** [comment]
@all Who is going for "Billing (across all endpoints)" on the back-end side? That's the only detail nobody is covering yet.
