### ISSUE TITLE
How to handle file moves in subscriptions?

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#110]
The allowed values for the `action` parameter for `openeo.files` subscriptions are `created`, `updated`, `deleted` ([code reference](https://github.com/Open-EO/openeo-api/blob/a781963510764bfa8dee847feca1bc531765c46d/subscriptions.json#L368)). What should happen if a file is moved/renamed? Issuing one `deleted` message for the old path and a `created` message for the new path would technically be correct, but wouldn't keep track of the connection between the two file names.

I would therefore suggest to add another item (`renamed`) to the `action` enum. The `path` field should contain the old name (so that scripts listening to changes of that file wake up when that name appears) and a `new_path` field should be specified (if and only if `action` is set to `renamed`).

File-specific subscriptions for the old file name should be automatically converted to the new file name, so that subsequent messages regarding that very file (even though it now has a new name) are still delivered, without the need of the user to "update" their subscription to the new name.

(Or is file renaming not a feature anyways? :thinking:)

**Comment by m-mohr** [comment]
Currently, file renaming is not supported by the API and therefore this type of event should never happen.

**Comment by m-mohr** [comment]
@christophfriedrich If you think renaming should be a thing in the API, please open a spearate issue for it. If it gets approved then the renamed action will be added anyway. Therefore I'll close this for now.
