### ISSUE TITLE
File-specific subscriptions

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#119]
It might be handy to have file-specific subscriptions, so that one can e.g. watch what happens to a certain script.

The subscribe payload could look like this:

    {
        "topic": "openeo.files",
        "path": "myscript.js"
    }

**Comment by m-mohr** [comment]
I don't really see much use-cases for file specific subscriptions. Global File subscriptions are probably only meant to update local representations of the cloud file system, e.g. when a list of available files is shown in the browser. Other than that I don't see for what this should be used. Any examples?

**Comment by m-mohr** [comment]
Closed for now as the WebSocket-based Subscriptions API won't be part of 1.0. We may revisit this in the future.
