### ISSUE TITLE
camelCase or snake_case in client guidelines

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#124]
I only just realised that the method names in the client guidelines are given in camelCase, but the parameters are given in snake_case. Is this on purpose?

The doc explicitly states that the "case to your liking" policy "applies for all names, including scopes, method names and parameters". It doesn't explicitly say "but please stick to ONE casing", but I'm pretty sure that this is implied and therefore suggest that the examples should stick to one casing, too.

**Comment by m-mohr** [comment]
Should be fixed by the referenced commit.
