### ISSUE TITLE
A bit of confusion concerning the `hasFeature` method

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#125]
In the Client Guidelines, in *Scope `Capabilities`* ([Link](https://open-eo.github.io/openeo-api/v/0.3.0/guidelines-clients/#scope-capabilities-content)), there is the `hasFeature` function:

> Description: Check whether a feature / endpoint is supported.
Field: `endpoints > ...`
Client method: `hasFeature(method_name)`

The parameter is explained as:
> **method_name** in `hasFeature`: The name of a client method in API scope.

Questions:
1. What is meant with "API scope"? All the scopes that have "API" in brackets in that document? Strictly speaking, the doc doesn't define a scope named "API"; that abbreviation only appears in the paragraph that says that "There are three types of scopes". (The terms "scope" vs. "type of scope" seem to be used interchangeably, which is confusing.)
2. Due to "Field: `endpoints > ...`", my first assumption before reading the parameter explanation was that this will be some method that just checks whether a certain key exists in the array, e.g. (simplified) `endpoints.includes(method_name)`. But now it seems a lot more complex: Do I understand correctly that the `hasFeature` is supposed to 'translate' between (1) API method names and (2) endpoint path + HTML method name combinations? So e.g. `hasFeature("describeAccount")` checks whether `GET /me` is in the Capabilities?

BTW the name of the ->>> `methods` <<<- key in the `endpoints` array is another source of confusion when we're talking about a parameter called `method_name`.

PS: After writing down this issue, the doc doesn't seem as confusing to me anymore, but it *was* confusing at first, so I'll submit this issue anyway.

**Comment by m-mohr** [comment]
1. Yes, we should differentiate between 'scope' and 'type of scope'. The API scope is defined in the paragraph you mentioned.
2. Client library users don't know about the API endpoints. Therefore we need to translate the client method names to the API endpoints or it would be completely confusing for a user. That's the reason behind it and was the only reasonable way I found to implement this feature detection except defining a lot of isXxxSupported() methods.
3. It's bastically client method vs HTTP method. It's probaly only confusing for client devs, all other don't see the both 'worlds', but I have no real solution except improving the client library guidelines by adding a short clarification.

**Comment by christophfriedrich** [comment]
1. will do!
2. ok, sounds very reasonable
3. yeah true, will consider this when doing 1.

**Comment by m-mohr** [comment]
@christophfriedrich Can you work on this until end of the month, please?

**Comment by christophfriedrich** [comment]
Done :heavy_check_mark:
:arrow_right: PR

I re-wrote much of the scopes section to solve 1, among other things changed the terminology to "scope categories". Points 2 and 3 didn't need much extra text - I think they are sufficiently explained by the example I added.

**Comment by m-mohr** [comment]
Thank you, PR got merged.
