### ISSUE TITLE
Was createProcessGraph forgotten in the client guidelines?

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#127]
There is a `POST /process_graphs` endpoint in the API, but there is no `createProcessGraph` method listed in the tables of the client guidelines. This differs from Jobs, Services and Files. Was this method forgotten or left out on purpose? If the latter: Why?

**Comment by m-mohr** [comment]
Thanks for spotting this. Was forgotten, can you make a PR for 0.4.0?
