### ISSUE TITLE
Property name for file PATH shouldn't be "name"

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#133]
The property that holds the file paths in API responses is currently called "name". It has the description "Path to the file" ([reference](https://open-eo.github.io/openeo-api/v/0.3.0/apireference/#tag/File-Management/paths/~1files~1{user_id}/get)).

It should be something more self-speaking, like "path".

When people talk about a "name" of a "file" they're usually just talking about the *name* (i.e. `asdf.txt`), and not about the directories that file resides in.

**Comment by m-mohr** [comment]
Thanks, fixed.
