### ISSUE TITLE
HTTP methods for /capabilities

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#15]
It might happen that an endpoint specified in /capabilities supports multiple HTTP methods, but only one of them is implemented. How is this specified in the capabilities? Currently it seems to be try & error...

**Comment by appelmar** [comment]
Something simple as in the following example response should solve this:

```
{
  "/data" : ["get"],
  "/data/{product_id}" : ["get"],
  "/jobs/{jobid}/" : ["get", "delete"]
}
```

Any objections?

**Comment by m-mohr** [comment]
I'm not sure whether it's a good idea to have JSON keys that are not alphanumeric.

If we want to avoid this, it would probably end up with something similar to this example:
```
[
  { path: "/data", methods: ["get"] },
  { path: "/data/{product_id}", methods: ["get"] },
  { path: "/jobs/{jobid}/", methods: ["get", "delete"] }
]
```

**Comment by m-mohr** [comment]
This should potentially also include whether authentication is required or not:
```
{
    "endpoints": [
        {
            "path": "/data",
            "methods": [
                "GET",
                "OPTIONS"
            ]
        },
        {
            "path": "/jobs/{job_id}",
            "methods": [
                "GET",
                "DELETE",
                "PATCH",
                "OPTIONS"
            ],
            auth: true
        }
    ]
}
```

auth: true => Authentication required
auth: false (or not mentioned) => Authentication not required

**Comment by m-mohr** [comment]
Implemented. Left out authentication as with the rework for #74 it probably becomes obsolete (=> every endpoint except `GET /` requires authentication with the method specified in the spec, except it is a publicly shared resource).
