### ISSUE TITLE
Use more programmer friendly response definitions

### ISSUE THREAD

**Issue by mundialis-dev** [Open-EO/openeo-api#152]
The response definition for a specific EO dataset/collection includes 
identifier with a colon ":" in their names like:  "eo:instrument" or "sci:citation":

Using a colon in identifiers should be avoided, this is hard to implement in the backend response.
It would be more meaningful to have a dedicated "eo" and "sci" object in the response that include the required variables.

In several languages it is not possible to have colons in variable names, hence it is not possible to use common serialization techniques to transform a class or map into a JSON response using the approach that is now defined in v0.3.1.

For example: The openEO API collection extent definition can be implemented in Python as:

```
class Extent(JsonableObject):
    def __init__(self, spatial: Optional[Tuple[float, float, float, float]] = None,
                 temporal: Optional[Tuple[str, Optional[str]]] = None):
        self.spatial = spatial
        self.temporal = temporal
```

Instances of this object can be filled with data and then serialized. 
Requiring ":" in variable names makes this approach impossible.

**Comment by m-mohr** [comment]
The double colons are coming from the STAC spec we are adopting for collection metadata. If you really want to change this, you need to open this issue in the stac-spec repository, but honestly I don't think this will be changed. I'm not a Python programmer, but I know there are python-based STAC implementations so guess there's a way around this problem.

**Comment by mundialis-dev** [comment]
I opened an issue in the STAC spec repo:
https://github.com/radiantearth/stac-spec/issues/357

**Comment by m-mohr** [comment]
Thanks, issue will be tracked there.
