### ISSUE TITLE
Clients: More semantic way to return collections/processes/etc. + the `links`

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#155]
In the JS client, I implemented the `listCollections` method like this:

    listCollections() {
		return this._get('/collections')
			.then(response => response.data);
	}

i.e. I directly pipe through the response from `/collections`, which is an object with two properties: `collections` and `links`:

````
{
  "collections": [
    {
      "name": "Sentinel2",
      ...
    },
    ...
  ],
  "links": [
    {
      "rel": "self",
      "href": "http://giv-openeo.uni-muenster.de:8080/v0.3/collections"
    },
    ...
  ]
}
````

This means that if a client is interested in the collections array, the method call looks like:

    connection.listCollections().then((collections) => console.log(collections.collections))

or

    const collections = await connection.listCollections();
    console.log(collections.collections);

I don't like this `collections.collections` thing. I would find it more semantic and intuitive if **a function called `listCollections` actually returns a list (i.e. an array) of collections**, without the need to access yet another property in an object. I.e. I would like to change my implementation to be:
`then(response => response.data`_**`.collections`**_`);`

However, then there's no way to access those `links`. My first impression is that no-one needs them anyways, but after checking with Matthias I seem to be wrong.

So I can imagine three ways to handle this issue:
1. Have `listCollections` return the collections array and introduce another method `listCollectionLinks` that returns the links array
2. Have `listCollections` return the collections array by default and introduce an optional parameter `returnLinksInstead = false` (or similar) so that it doesn't return the collections at all but only the links array
3. Leave it as it is and bear with it

This issue applies to all endpoints that return an array + links, i.e. also processes, process graphs, jobs, services, files...

**Comment by m-mohr** [comment]
I see the point, some thoughts:
1. Doesn't make much sense as this is not extensible, i.e. if an extension introduces more root fields we need to introduce more methods. Not a good idea.
2. If we go this way, I'd prefer to have a parameter that switches between collections only and the full response. Your parameter is not extensible, similar to what I said for bullet point 1.
3. I see why this feels odd, but at least it is extensible and works for now. And if you rename the variable from collections to response or so, it doesn't feel too bad for me. ;-)

In the end all this is pretty much syntactic sugar and not a real issue with functionality.

**Comment by christophfriedrich** [comment]
> not a real issue with functionality

true, but:

> have a parameter that switches between collections only and the full response

I like that! Let's name it `returnFullResponse` and set it to `false` by default.

I think this adds another bonus: If the API format changes in the future, we can still map wherever the `collections` array is then to be returned by default, and if the user opted in to get the full response he's responsible for adapting to the change.

**Comment by m-mohr** [comment]
Setting the default to false would make more sense for Python and R as CLI, but not so much for JS. For CLI this makes sense as the results should be easily readable by users in that environment, but JS in contrast is rarely used as CLI so there is tooling around it that hides that "complexity". For example, the Web Editor will most of the time set this parameter to true anyway as it needs the links anyway - for pagination, displaying the additional resources etc..

**Comment by m-mohr** [comment]
We realized that this issue is language-specific as not all languages benefit from this "solution". For example, in object-oriented languages with support for "Iterables" you can simply return a class that implements Iterable and allows using the object as array of collections. That feels as if the object would be an array and you can still provide the information such as links in additional methods.

Clients can still introduce a parameter such as "extended" or "includeAdditionalProperties" if required. But the client development guidelines should not cater for that as it would only solve implementation issues for some languages, which are not required for others.
