### ISSUE TITLE
Add `free: true|false` property to billing plan

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#157]
For the openEO Hub I thought of a search option like "Exclude backends without a free plan". I currently implemented this by checking whether the `plans` array contains a plan by the name of "free" or not, but obviously this is not fail-safe at all. E.g. a backend may name its free plan "basic", or something completely different.

@m-mohr suggested that we could add a boolean `free` flag to the `plan` object. I think that's a good idea, and the flag should even be required. It would remove the ambiguity out of plan names and thus facilitate this search feature, which I consider to be a use case that is not too rare.

**Comment by m-mohr** [comment]
Implemented as required boolean `paid` flag.
