### ISSUE TITLE
Open date ranges: Is there a use case for `extent.temporal[0] = null`?

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#159]
The API says about temporal extent:
> Open date ranges are supported and can be specified by setting one of the times to null.

I clearly see it makes sense to set the end date to `null`: for collections that are still being updated.

But is there a use case for the opposite? The start date of a collection is always known, isn't it? And can thus always be set, can't it?

A quick scan through the Earth Engine driver's `/collections` array shows that none of its currently 419 collections has its start date set to `null` (while the end date is `null` for 198).

**Comment by m-mohr** [comment]
I don't know whether there's a use case for it, but we can't validate individual elements of an array, i.e. we can't only allow the second element to be null in JSON schema/OpenAPI. Constraints in descriptive texts are always problematic. To simplify things we simply allow a null starting date as it shouldn't be a problem for the implementation, I assume.

**Comment by christophfriedrich** [comment]
Okay, now I understand why it was done this way. I don't see a general problem in it, I just stumbled across it when typing [this somewhat strange line of text](https://github.com/Open-EO/openeo-hub/commit/fe4b0837b213f2db28fd9a85ce6e547dc149736d#diff-d18730cc2118224744504b17f1811a4aR93) while working on nicer temporal extent output in the Hub.

I'd like to keep this issue open (for another week or so?) -- maybe someone else happens to know a use case for it.

**Comment by m-mohr** [comment]
The only use case I can think of is ingesting a huge archive of data over months or so (like Google did with Landsat, I think), which starts to ingest at present. Then the current "start date" is unknown. I don't see many other cases...

Rgarding your formatting, you could maybe go with something like:
Label: Temporal extent
Instance of time: <formattedTimestamp>
Missing end time: <formattedTimestamp> until present
Missing start time: Until *or* Before <formattedTimestamp>
Date range: <formattedTimestamp> until *or* - <formattedTimestamp2>
