### ISSUE TITLE
/preview does not really align with use cases of sync api calls

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-api#162]
In 0.3.x, synchronous API calls now go through '/preview' (https://open-eo.github.io/openeo-api/v/0.3.1/apireference/#tag/Job-Management/paths/~1preview/post)
The use case of synchronous api calls goes beyond previewing stuff:
- retrieving time series in a synchronous manner
- simply downloading an image, for analysis 
- any process that generates a meaningful result without requiring asynchronous handling

What was wrong with 'execute'?

**Comment by jdries** [comment]
Thanks for the explanation, it clarifies the reasoning. As already stated, I have a bit of a different view on relevance of the different calls:
* synchronous calls (preview/execute) are basically the way of the future. Both GEE, SentinelHub, and some services at VITO already show that meaningful information can be returned within the timing constraints of a synchronous call. 
* asynchronous calls (batch jobs) are also needed, but especially for backends that support UDF's, where the performance of the process graph is out of the control of the backend. I don't see it as a must-have feature for every backend implementation. 
* web services for viewing are also very relevant, but there I've been thinking about supporting it also in a stateless manner, where the process graph is sent along with each request in a custom parameter. This way of working is also supported by SentinelHub. It allows a backend to work without requiring user management or state.

Now all of the above is just context to explain why it goes beyond previewing. So for naming, given that we now use `'result':true`in our process graph, would `/result` be an option?

**Comment by m-mohr** [comment]
> * synchronous calls (preview/execute) are basically the way of the future. Both GEE, SentinelHub, and some services at VITO already show that meaningful information can be returned within the timing constraints of a synchronous call.

Good point.

> * asynchronous calls (batch jobs) are also needed, but especially for backends that support UDF's, where the performance of the process graph is out of the control of the backend. I don't see it as a must-have feature for every backend implementation.

So how does the user know that UDFs may not be the best options in synchronous calls?

> * web services for viewing are also very relevant, but there I've been thinking about supporting it also in a stateless manner, where the process graph is sent along with each request in a custom parameter. This way of working is also supported by SentinelHub. It allows a backend to work without requiring user management or state.

I personally don't like those ridiculously long URLs, but could still be something we want to standardize nevertheless, so could be worth a separate issue.

> Now all of the above is just context to explain why it goes beyond previewing. So for naming, given that we now use `'result':true`in our process graph, would `/result` be an option?

I'm sure I considered this option when renaming the endpoint and rejected it for some reason, but at the moment I think that could be an option. It seems consistent with the jobs, too (`POST /jobs/:id/results` vs `POST /result`).  Though it would be even more intuitive when renamed to batch_jobs or so.

**Comment by jdries** [comment]
The user will have to learn either by documentation or by clear error messages when to use what endpoint. Unfortunately, a call that works synchronously on one backend, might not work on another one, and there's not much we can do about that. (Except that 'slow' backends will simply not be used a lot by people looking for interactive queries.)

**Comment by m-mohr** [comment]
Okay, I renamed it to `/result` in dev and changed the method name in the client dev guidelines to `computeResult()`.
