### ISSUE TITLE
Clear definitions of collections and datacubes are missing from the glossary

### ISSUE THREAD

**Issue by mirt001** [Open-EO/openeo-api#168]
This issue is related to issue #26, but more specific.

The way I understand it, is that collections are available to be used, as datacubes. This would mean that the data is a collection up to the moment is loaded, and afterwards you can only work with it as a datacube.

This kind of information should be available in the glossary, together with more explicit standalone definitions of datacubes and collections.

**Comment by m-mohr** [comment]
Good points, could you come up with a Pull Request for it?

**Comment by m-mohr** [comment]
I added a paragraph describing the workflow (collections => data cube). @mirt001 Is that good enough? Otherwise it would be good if you could come up with a Pull Request for it.

**Comment by m-mohr** [comment]
Considered to be done until further input from @mirt001 .
