### ISSUE TITLE
/result: how to specify output format

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-api#178]
The api docs for /result say (0.4.0):

> the result will be downloaded in the specified format
https://open-eo.github.io/openeo-api/v/0.4.0/apireference/#tag/Process-Graph-Management/paths/~1result/post

But I don't see where to specify this format exactly. 

In 0.3.0, this was done by the output parameter:
https://open-eo.github.io/openeo-api/v/0.3.0/apireference/#tag/Process-Graph-Management/paths/~1preview/post

Note that for batch jobs, I believe this was replaced by the save_result process:
https://github.com/Open-EO/openeo-processes/blob/master/save_result.json
It might be a good idea to reference this process in the batch job documentation.

**Comment by m-mohr** [comment]
In the process graph, the `save_result` process.

**Comment by m-mohr** [comment]
Added a short explanation as requested.
