### ISSUE TITLE
Chunked Datasets / Collections

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#180]
Our back-ends provide their datasets differently. For example, GEE has a single Sentinel-2 L1C collection, which has been merged based on several assumptions (e.g. projections, resolution). EURAC (@aljacob) has multiple collections for Sentinel-2 L2A. The data is grouped by projection and resolution. Therefore the bands are spread across collections. Having these differences leads to different processing steps.

An example, I'd like to compute an NDVI for Bands B8A and B4. For GEE we just need to load a single collection, filter the bands and can compute the NDVI. AT EURAC, we need to load two collections, resample one of the collections, merge the collections and only after these steps we can filter the bands and compute the NDVI. That said, the process graphs can't be transferred easily between back-ends.

We need to think about a solution. Currently, we have the process [find_collections](https://open-eo.github.io/openeo-api/v/0.4.0/processreference/#find_collections), which could somewhat solve the issue. For GEE it would return the same collection though and merging would lead to an overhead.

**Comment by GreatEmerald** [comment]
The WUR team (Andrei, Milutin and I) discussed this issue from the users' perspective, and we think there are two ways to handle it:

1. Do the resampling on the fly, but send the client a warning/info message saying that a particular collection has been resampled in this way to make sure that the projections match. This makes life easier while still being very explicit about the assumptions made. However, the number of warnings may be intimidating to some casual users (e.g. government) as they may think they are doing something wrong.
2. Do the resampling on the fly, and put the notes about assumptions into a log file that the user can review at their leisure. This is a less explicit way of doing it compared to option 1, so it's less intimidating, and it's still more explicit about what's going on than the approach of GEE.

The option to just stop and throw an error and wait for users to explicitly resample their collections was not favoured by anyone in our team.

In addition, we think there is no correct solution and it is ultimately a political issue about how we want to position OpenEO and what users we want to target primarily: those who want precise full control over everything (which favours the "stop with an error" option) or those who prefer convenience (which favours above option 2), or something in-between. As such we feel that it would be a good idea to solve this issue at the project board level instead.

**Comment by mkadunc** [comment]
IMO openEO does not need to guarantee 100% compatible data representation at all back-ends, resulting in no-modification portability of process graphs... If we wanted to go in this direction, it would be a lot of unnecessary work for all backend implementors.

Harmonisation of various aspects of collections between different backends, and various enumerated names for commonly-used concepts, is already being discussed in https://github.com/Open-EO/openeo-api/issues/52  - the same kinds of discussions that answer "What does the well-known value 'satellite:Sentinel-2' refer to?" could answer "What is the structure of a collection with well-known name 'Sentinel-2 L1C'?" : the answer, if provided within openEO, will provide some constraints for all collections with that name (e.g. that it has 13 bands), but it shouldn't cause any back-end to be invalid as a result...
