### ISSUE TITLE
OpenAPI: Format issues

### ISSUE THREAD

**Issue by bgoesswe** [Open-EO/openeo-api#181]
During the testing of the compliance tests on the back ends, I found out that there seems to be problems with formats defined as "url" (using openapi.json v0.4.0).
e.g. "format": "url"
When I changed this to "uri", according to [https://swagger.io/docs/specification/data-models/data-types/](data-types), it works. 
But I am not sure if the change is ok, or the "url" entries are on purpose.

I also had problems with empty "security" blocks, but since it seems ok by the openapi spec, it might be an issue of the validation tool. But if there is no need could we remove them ? 
e.g. Capabilities
"security": [
          {}
],

**Comment by m-mohr** [comment]
URI and URL are different things, but indeed `url` is not one of the pre-defined formats. Nevertheless, it should be okay to define custom formats and I guess the tooling just doesn't support them. If we have tooling that gives us great value and absolutely requires it, I think we can change it. Beforehand we should check whether there's a way to allow `url` in tooling. Are you talking about the Go-based validator?

We can't remove the empty security block though. They are required to indicate that no authentication is required. So I guess filling an issue with the validation tool makes much more sense. In the meantime we could just use a slightly modified OpenAPI spec for this purpose only.

**Comment by bgoesswe** [comment]
Ok, then I think we can keep the security section and also the URL, I was just curious if it was by mistake or on purpose. 
Yes I am talking about the Go-based validator and since it is open-source (MIT) I can just simply change these things and write an issue at their repository.

**Comment by m-mohr** [comment]
@bgoesswe Maybe this helps to solve the URL issue: https://github.com/getkin/kin-openapi/issues/79
