### ISSUE TITLE
Process graph: Complex validation of array and objects that contain variables and other references

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#183]
This issue is a follow-up on #160 to keep track of issues we are facing with the new process graphs.

**1. Validation of array and objects that contain variables and other references**

An issue I am currently facing is that I can't easily validate arrays and objects that contain variables, references to results or callback arguments. Currently, I'm trying to implement a JSON Schema based approach for process graph validation where each argument of a process is validated against the JSON Schema that is specified for each parameter in the process specification. In theory, this works very well and in practice it does, too, unless you add variables and other references such as {from_node "abc"} in your process graph. The issue is that JSON schema expects something different and fails. 

For example, I'd like to load a collection by ID and restrict the temporal extent with a start date, both coming from a variable:
```
{
  process_id: "load_collection",
  arguments: {
    id: {variable_id: "collection", type: "string"},
    temporal_extent: [{variable_id: "start_date", type: "string"}],
    spatial_extent: null
  }
}
```
In theory, this works well and I should be able to easily check whether the specified variable type is compatible with the schema specified from the argument. This indeed works in my implementation for the id by simply checking whether the parameter is a variable or not and then running the JSON Schema validaton or not. However, it doesn't for the temporal_extent as the object is inside an array and therefore the JSON Schema based validation fails. I'd need to make sense of the JSON Schema and interfere with the JSON Schema validator. With most libraries this is not very easy or impossible. Therefore it seems hard to implement in the validation step. Additionally, it is also hard to construct in the Web Editor. It shouldn't be too much of a problem in the other CLI-based libraries though.

The problems described here don't only apply for variables, but also for referring to results and callback arguments. We need to think about how we want to handle this. I don't have a good solution yet and proposals are more then welcome.

**If you have other issues, please report them, too.**

**Comment by jdries** [comment]
In our implementation, the validation of arguments happens after they are fully resolved. So first we convert the json tree into the actual graph, and then start resolving the arguments. We can then do all types of custom input checking when arguments are resolved. 
I think json schema is mostly useful for a first static analysis, but it is indeed limited as to what can be checked in more complex cases.

**Comment by m-mohr** [comment]
I think we can solve this in implementation by just going recursively through the schema and replacing any object with a type in it with a oneOf that checks for the different object types and the original schema.

For example, the following schema:
```json
{
  type: "array",
  items: {
    type: "string"
  }
}
```
would translate into:
```json
{
  oneOf: [
    {
      $ref: '#/path/to/from_node_object'
    },
    {
      $ref: '#/path/to/from_argument_object'
    },
    {
      type: "array",
      items: {
        oneOf: [
          {
            $ref: '#/path/to/from_node_object'
          },
          {
            $ref: '#/path/to/from_argument_object'
          },
          {
            type: "string"
          }
        ]
      }
    }
  ]
}
```

This looks rather complicated now, but generating it is quite simple in code.
