### ISSUE TITLE
Boolean field `production` should be part of capabilities too (not only in well-known document)

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#184]
The information whether a backend instance is in production state or not can so far be determined via `/.well-known/openeo`, but not via the capabilities document of the service itself. I would like to add this field to the capabilities document.

- The current state is not consistent with the `api_version` field which is repeated in both documents
- If someone knows only the URL of the backend itself it's harder than necessary to find out whether it is in production state or not
- The well-known document could then be generated from just the contents of the individual capabilities documents
- Removes the need to look at well-known document to get **all** information about backend

**Comment by m-mohr** [comment]
Makes sense, added.
