### ISSUE TITLE
0.4.1: Required list has not defined properties: ['sar:pass_direction']

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#187]
The openAPI Spec validator (https://github.com/p1c2u/openapi-spec-validator) raises an issue on openeo api version 0.4.1. Using docker for easy "reproducibility": 

    $ git describe --all
    tags/0.4.1
    $ docker run --rm -it -v${PWD}:/app -w/app python bash
    root@d655a5560e59:/app# pip install openapi-spec-validator
    ....
    
    root@d655a5560e59:/app# openapi-spec-validator openapi.json 
    Required list has not defined properties: ['sar:pass_direction']

(same result on 0.4.0 FYI)

**Comment by m-mohr** [comment]
Thanks, that is indeed an undefined property. If it breaks anything just remove it from the file. I'll investigate why our validation tool - speccy - doesn't report such errors and will remove the faulty line in the next version.

**Comment by m-mohr** [comment]
Fixed on the dev branch.
