### ISSUE TITLE
glossary doc: "spatiotemporal" instead of "spatial" data cubes?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#188]
the glossary doc (https://open-eo.github.io/openeo-api/v/0.4.1/glossary/#spatial-data-cubes) discusses "spatial" data cubes, but shouldn't that be called a "spatiotemporal" cube as it has a time dimension?

**Comment by m-mohr** [comment]
Have no strong preference regarding this issue and would be happy to merge a PR. There may be data cubes which don't have a spatial dimension any longer, but usually they should be spatiotemporal.

**Comment by edzer** [comment]
I also have no strong preference. I believe that with "spatial data cube", most people will think of spatiotemporal data.

**Comment by soxofaan** [comment]
I understand that in regular documentation "spatial" is clear enough to a seasoned EO audience (which I am not at the moment). But in the glossary it might be useful to be a bit more explicit and wider reaching.
