### ISSUE TITLE
docs: missing jobs.md

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#190]
both `docs/gettingstarted-backends.md` and `docs/gettingstarted-clients.md` refer to `jobs.md` which does not exist (yet)

**Comment by m-mohr** [comment]
Thanks for reporting this issue. The references are left overs, which I forgot to remove. The descriptions of jobs are now part of the glossary in the section "data processing modes". I updated the getting started guides accordingly.
