### ISSUE TITLE
docs: 404 page is broken

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#191]
(related to #190)  the current 404 page is broken:
- layout is missing
- links in navigation do not work

e.g. go to https://open-eo.github.io/openeo-api/v/0.4.1/foo/bar

screenshot (with webdev tools open on the right):
![Screenshot from 2019-06-26 11-52-53](https://user-images.githubusercontent.com/44946/60170749-664d9980-9809-11e9-8977-7f72e973cdf5.png)

**Comment by soxofaan** [comment]
I haven't looked into detail yet, but it's probably this mkdocs issue: https://github.com/mkdocs/mkdocs/issues/1598

**Comment by m-mohr** [comment]
I don't fully know how to solve it yet and it doesn't seem very important, too. It seems we would need to set an absolute url for mkdocs (site_url), but that's not available in this context as it depends on the branch. I guess we could hack a solution into the travis.yml, but I'm not sure whether it's worth the effort at the moment.

**Comment by m-mohr** [comment]
Fixed for newer versions after restructuring the whole documentation.
