### ISSUE TITLE
Validate all processes in a process graph

### ISSUE THREAD

**Issue by klimeto** [Open-EO/openeo-api#196]
Dear developers,

We (@kempenep) developing the jeodpp openeo driver and currently got stacked in the API method to insert  a job with its basic metadata and process graph at POST /jobs .

Before I insert any job into our backend I would like to validate each node containing a subprocess of the entire graph. 

I am not sure if this repo is a correct one to ask this question, but what is the standard procedure of validating each process listed in this repo and request to be a node of users graph?

First I thought i could use an object schema from a standard process description JSON e.g. load_collection, but then I found that a single process contains more than 1 schema definitions.

I would like to use a standard python3 library jsonchema, but for this I would need to generate a valid json schema document based on schema sections within a process description.

How other teams deal with process graph validations?

Many thanks for your opinions,
Tomas

**Comment by m-mohr** [comment]
Hi @klimeto, 

fIrst of all, there are multiple implementations already. So if you are using JS or Python, it would be great if you could align your effort with any of the existing solutions. It doesn't make much sense to have multiple different process graph parsers for a single programming language all developed independently. For JS you can ask me, for Python you may speak with VITO @jdries, EODC @lforesta or mundialis @mundialis-dev. JS is ready to go, Python probably needs some more alignment and work in the future.

Regarding validation there are multiple steps. I'll give you some insights how I implemented it for JS:

In general, there are three steps:
1. Parsing
2. Validation
3. Execution

Parsing basically checks the general structure of the process graph and transforms it into a "native" JS graph that the application can process. This checks whether the process graph is an object of process nodes and each process node conforms to the specification (e.g. has a process_id and arguments, has a single result node, ...).

Validation checks whether the actual values are correct. First it checks whether the processes are actually available and then it validates each argument against the JSON schemas. This also includes checking whether the return value and the arguments requesting a return value with `from_node` are compatible.

Validation should also check whether `from_argument` has a correct value, whether the process graph variables are valid and it should recurse into the callbacks. Each callback is a process graph on its own and therefore the same procedures can be used as for the "main" process graph.

I guess we could probably also come up with a JSON schema, I think I'll give that a try tomorrow. The JSON schema will not be enough for full validation though.

That's a very rough idea. Feel free to ask if anything is unclear.

**Comment by m-mohr** [comment]
Here's a repo that could be used for Python commons: https://github.com/Open-EO/openeo-python-driver

Below you can find a process graph JSON schema for validation. It checks the basic structure of a process graph.

**Important notes:**
1. Arguments and return values still need to be checked against the schemas in the process descriptions.
2. It is not checked whether there's exactly one `result: true` per process graph.
3. It doesn't check whether the values for `from_node`, `from_argument` or `process_id` are correct. There's a custom format `process-id`, which could make implementation/validation easier though.
4. It doesn't check the content of arrays and objects. These could include variables and other references (from_node, from_argument, ...). See also issue #183.
5. This JSON Schema is probably good enough for a first version, but should be revised and improved for production.

```json
{
  "$schema":"http://json-schema.org/draft-07/schema#",
  "title":"Process Graph",
  "description":"A process graph defines a graph-like structure as a connected set of executable processes. Each key is a unique identifier (node id) that is used to refer to the process in the graph.",
  "allOf":[
    {
      "$ref":"#/definitions/process_graph"
    }
  ],
  "definitions":{
    "process_graph":{
      "title":"Process Graph",
      "type":"object",
      "additionalProperties":{
        "$ref":"#/definitions/process_node"
      }
    },
    "process_node":{
      "title":"Process Node",
      "type":"object",
      "required":[
        "process_id",
        "arguments"
      ],
      "properties":{
        "process_id":{
          "$ref":"#/definitions/process_id"
        },
        "result":{
          "type":"boolean",
          "default":false
        },
        "description":{
          "type":[
            "string",
            "null"
          ]
        },
        "arguments":{
          "$ref":"#/definitions/process_arguments"
        }
      }
    },
    "process_arguments":{
      "title":"Process Arguments",
      "type":"object",
      "additionalProperties":{
        "$ref":"#/definitions/process_argument_value"
      }
    },
    "process_argument_value":{
      "title":"Process Argument Value",
      "anyOf":[
        {
          "type":"null"
        },
        {
          "type":"object",
          "title":"Object"
        },
        {
          "type":"string",
          "title":"String"
        },
        {
          "type":"number",
          "title":"Number (incl. integers)"
        },
        {
          "type":"boolean",
          "title":"Boolean"
        },
        {
          "type":"array",
          "title":"Array",
          "items":{
            "$ref":"#/definitions/process_argument_value"
          }
        },
        {
          "$ref":"#/definitions/variable"
        },
        {
          "type":"object",
          "title":"Result",
          "required":[
            "from_node"
          ],
          "properties":{
            "from_node":{
              "type":"string"
            }
          },
          "additionalProperties":false
        },
        {
          "type":"object",
          "title":"Callback Parameter",
          "required":[
            "from_argument"
          ],
          "properties":{
            "from_argument":{
              "type":"string"
            }
          },
          "additionalProperties":false
        },
        {
          "type":"object",
          "title":"Callback",
          "required":[
            "callback"
          ],
          "properties":{
            "callback":{
              "$ref":"#/definitions/process_graph"
            }
          },
          "additionalProperties":false
        }
      ]
    },
    "variable":{
      "title":"Process Graph Variable",
      "type":"object",
      "required":[
        "variable_id"
      ],
      "properties":{
        "variable_id":{
          "type":"string"
        },
        "type":{
          "type":"string",
          "enum":[
            "string",
            "number",
            "integer",
            "boolean",
            "array",
            "object"
          ],
          "default":"string"
        },
        "description":{
          "type":[
            "string",
            "null"
          ]
        },
        "default":{
          "anyOf":[
            {
              "type":"null"
            },
            {
              "type":"object"
            },
            {
              "type":"string"
            },
            {
              "type":"number"
            },
            {
              "type":"array",
              "items":{
                "description": "Any type is allowed."
              }
            },
            {
              "type":"boolean"
            },
            {
              "$ref":"#/definitions/process_graph"
            }
          ]
        }
      }
    },
    "process_id":{
      "type":"string",
      "format":"process-id",
      "pattern":"^[A-Za-z0-9_]+$"
    }
  }
}
```

I'll add this to the API docs, too.

**Comment by klimeto** [comment]
thanks a lot @m-mohr!

I integrated the first version of a [process graph schema](https://open-eo.github.io/openeo-api/v/0.4.2/processgraphs/#process-graph-validation) in jeodpp backend library.

Regarding the validation of an individual process arguments I would also like to use the json schema definitions included within a JSON metadata for individual processes description rather than doing it directly with python, since I think it would be easier for a future system admin to handle backend jobs metadata and corresponding validation using a simple web based editor. Naturally here we need to understand the restrictions of JSON schema standard.

The idea is to parse the graph, get the processes (process_id) and arguments and generate a valid schema for each argument within a process and use it to validate the contents of arguments. 

Ill try to work on it and report news.

**Comment by m-mohr** [comment]
Yes, you should definitely use JSON schemas from the process descriptions.
What restrictions are you thinking about?

**Comment by klimeto** [comment]
@m-mohr 
Could you please advice me how do you perform the validation of individual properties of a process, e.g. load_collection?

E.g. if I tried to validate spatial_extent with its schema extracted from the load_collection.json:

```json
 {
        "anyOf" : [ {
          "type" : "object",
          "title" : "Bounding Box",
          "format" : "bounding-box",
          "required" : [ "west", "south", "east", "north" ],
          "properties" : {
            "crs" : {
              "schema" : {
                "anyOf" : [ {
                  "type" : "integer",
                  "title" : "EPSG Code",
                  "format" : "epsg-code",
                  "examples" : [ 7099 ]
                }, {
                  "type" : "string",
                  "title" : "PROJ definition",
                  "format" : "proj-definition",
                  "examples" : [ "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs" ]
                } ],
                "default" : 4326
              },
              "description" : "Coordinate reference system of the extent specified as EPSG code or PROJ definition. Whenever possible, it is recommended to use EPSG codes instead of PROJ definitions. Defaults to `4326` (EPSG code 4326) unless the client explicitly requests a different coordinate reference system."
            },
            "base" : {
              "type" : [ "number", "null" ],
              "default" : null,
              "description" : "Base (optional, lower left corner, coordinate axis 3)."
            },
            "east" : {
              "type" : "number",
              "description" : "East (upper right corner, coordinate axis 1)."
            },
            "west" : {
              "type" : "number",
              "description" : "West (lower left corner, coordinate axis 1)."
            },
            "north" : {
              "type" : "number",
              "description" : "North (upper right corner, coordinate axis 2)."
            },
            "south" : {
              "type" : "number",
              "description" : "South (lower left corner, coordinate axis 2)."
            },
            "height" : {
              "type" : [ "number", "null" ],
              "default" : null,
              "description" : "Height (optional, upper right corner, coordinate axis 3)."
            }
          }
        }, {
          "type" : "object",
          "title" : "GeoJSON Polygon(s)",
          "format" : "geojson"
        }, {
          "type" : "null"
        } ]
      },
      "required" : true,
      "description" : "Limits the data to load from the collection to the specified bounding box or polygons.\n\nThe process puts a pixel into the data cube if the point at the pixel center intersects with the bounding box or any of the polygons (as defined in the Simple Features standard by the OGC).\n\nThe coordinate reference system of the bounding box must be specified as [EPSG](http://www.epsg.org) code or [PROJ](https://proj4.org) definition.\n\nThe GeoJSON can be one of the following GeoJSON types:\n\n* A `Polygon` geometry,\n* a `GeometryCollection` containing Polygons,\n* a `Feature` with a `Polygon` geometry or\n* a `FeatureCollection` containing `Feature`s with a `Polygon` geometry.\n\nSet this parameter to `null` to set no limit for the spatial extent. Be careful with this when loading large datasets!"
    }
```

using Python jsonschema.Draft7Validator I did not manage to validate it.

I seen you're using ajv, but could not get our of your code what is the entire $schema string you are sending to validate with?

Thanks a lot for help!

By restrictions I meant a usage of a custom json schema "format" types e.g. bounding-box, geojson, etc.

**Comment by m-mohr** [comment]
> using Python jsonschema.Draft7Validator I did not manage to validate it.

@klimeto What error did you get?

> Could you please advice me how do you perform the validation of individual properties of a process [...]
> I seen you're using ajv, but could not get our of your code what is the entire $schema string you are sending to validate with?

I'm adding `http://json-schema.org/draft-07/schema#` as `$schema` property to the schemas.
Other than that, I'm adding custom validators for each of the custom formats, see "[openEO specific formats](https://open-eo.github.io/openeo-api/draft/processes/#openeo-specific-formats)" for a full list.
Many of them (including `bounding-box`) simply return true for everything as all validation I could do is already done by the schema itself, but for `collection-id` for example I am checking against the list of available collections. For `geojson` one could check against the GeoJSON schema (and we may in future just `$ref` the official schema).


> By restrictions I meant a usage of a custom json schema "format" types e.g. bounding-box, geojson, etc.

Validators (in theory) should simply skip unknown formats, but it seems many don't do that. I had to register all types in ajv, and Bernhard had to do the same in kin.
