### ISSUE TITLE
share resources like process graphs, services or jobs publicly as a backend provider or user

### ISSUE THREAD

**Issue by aljacob** [Open-EO/openeo-api#206]
it should be possible to define resources for public use, for easy propagation of tutorial and example material. Clients like the editor should then also have the possibility to optionally visualize public or freely accessible resources such as example process graphs.

**Comment by m-mohr** [comment]
Sharing them will be part of #85, this issue focuses on making a list of public resources available.

**Comment by m-mohr** [comment]
Will be tackled as part of #85.
