### ISSUE TITLE
Replace RasterCollectionTile with Hypercubes

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#210]
in the [collection metadata](https://open-eo.github.io/openeo-api/apireference/#tag/EO-Data-Discovery/paths/~1collections~1{collection_id}/get), the `properties/cube:dimensions` item is currently defined as an object (aka mapping/dict). 
In some languages (e.g. python before 3.7) there are by default no guarantees about the item order in mappings/dicts.

Could this pose a problem?
Or is the dimension order just an implementation detail that does not need to be exposed to the end user?

**Comment by m-mohr** [comment]
We refer dimensions only by name, never by order (I think). So I think it shouldn't be a problem for the  user and is not exposed to the user.

**Comment by mkadunc** [comment]
I agree that it shouldn’t matter inside openEO, but it might be worthwhile to have another look at how it’s handled on the boundary (export, UDF invocation etc.).

I’m not a fan of verbose metadata, but exposing some info about the internal organisation of the cube to the users might help them understand the performance characteristics of their process graphs.

**Comment by m-mohr** [comment]
@mkadunc Any concrete thoughts on this? I wouldn't really know what to have a look at taking your comment into account. There's already cube:dimensions in the metadata. How could that be improved?

For UDFs, I guess there's an issue on a very similar matter: https://github.com/Open-EO/openeo-udf/issues/14

**Comment by mkadunc** [comment]
e.g.: https://github.com/Open-EO/openeo-udf/blob/master/src/openeo_udf/functions/raster_collections_reduce_time_median.py
- the code assumes that time will be the dimension `0` in the data that is provided;

I don't know enough about UDF interfaces to analyse whether such assumptions would 'leak' into the process graph (effectively causing the graph to run on some backends but not others) or whether this is something that the backend takes care of when calling UDFs (in which case the backend probably needs to prepare data in the correct format based on UDF's metadata)

**Comment by m-mohr** [comment]
Good point. We need to align the UDFs with the rest of the API.
@huhabla @flahn Could we have named dimensions in the UDFs so that they align with the processes and API and users don't need to keep track of the axis order?

**Comment by m-mohr** [comment]
Discussed in 3rd year planning: RastercollectionTiles (which only have cube dimension access by index), will be replaced by Hypercubes, (which allow cube dimension access by name).
