### ISSUE TITLE
Account for legal issues?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#212]
We had a comment at the PhiWeek workshop that we should inform the user that there's data passed to a third party through openEO, e.g. to GEE or Vito. So we should see to which extent and how we inform the user about legal and property issues (terms of services, ...)...

**Comment by edzer** [comment]
Suggestions:
* for GUIs: add a check button, by default unchecked, that says "I agree with the terms of service of this backend" for those backends that have a ToS
* for CLI clients: add an argument `I_agree_to_terrms_of_service`, by default FALSE, that needs to be set to TRUE, as part of the `connect` command, when existing and required.

**Comment by m-mohr** [comment]
In addition, we can allow providers to add links to ToS / GDPR / ... with respective rel types in the capabilities.

**Comment by soxofaan** [comment]
> for CLI clients: add an argument I_agree_to_terrms_of_service, by default FALSE, that needs to be set to TRUE, as part of the connect command, when existing and required.

as a developer, this feels like a silly approach :)

Couldn't we just tackle it during the "registration" of a user (the first time a backend sees a user): forward to a page to consent/agree. For example:
- user makes API request
- backend detects that user didn't consent yet and throws an "LegalConsentRequired" error, with link to consent page or something alike
- client forwards user to consent page
- when user agrees, backend flags user as "has given consent"

**Comment by m-mohr** [comment]
@soxofaan It's still up to the back-end to decide. The current draft just gives the possibility to define terms of services and privacy policies in the capabilities and obliges the clients to ask for consent (in whatever form) when they are set. If the back-end doesn't set this (because it's part of the registration process) the client doesn't need to promt for consent.

At the moment the client doesn't even send the consent to the back-end, but that may still need to be considered.

**Comment by m-mohr** [comment]
I'll leave it as it is for now. Communicating the consent to the server can be considered again for 1.0-final.

**Comment by m-mohr** [comment]
As an example, here's the implementation in the Web Editor:

![image](https://user-images.githubusercontent.com/8262166/79577241-aea1b500-80c4-11ea-8838-9b79ba2f8fa8.png)

**Comment by m-mohr** [comment]
@flahn @bgoesswe @soxofaan @jdries How are you planning or have you implemented the TOS / privacy policy links from the capabilities in the CLI libraries?
