### ISSUE TITLE
What to send as API bearer token: access token or id token?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#219]
This question was raised in #201 but I think it deserves its own ticket:

> What to send as Bearer Token? access_token (response_type = 'token) or id_token (response_type = 'id_token')?

**Comment by soxofaan** [comment]
For example: there are various suggestions to use the id_token as bearer token in the openEO API requests:

> After some more discussions with @aljacob , it seems we need to send the id_token, not the access_token. 
--  @m-mohr https://github.com/Open-EO/openeo-api/issues/201#issuecomment-527031784

> in the example I use the "Authorization Code" as a Grant Type, in order to be able to get an id_token (instead of an access_token),
-- @lforesta   https://github.com/Open-EO/openeo-api/issues/201#issuecomment-535884600 

> Upon receiving the id_token, the client send the request to the back-end with this token embedded in the header.
-- @lforesta  https://github.com/Open-EO/openeo-oidc-examples

**Comment by soxofaan** [comment]
However, when googling around I typically find the recommendation to use the access token (and not the id token) as bearer token in API requests.

For example take https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis
I assume the following mapping while reading this:
- "App/Application" = openEO client (a jupyter notebook using python client code, or the openEO web editor)
- API = openEO backend, exposing functionality through openEO API

> id token is meant for app only

So only the openEO client is supposed to consume the id token

> Access token purpose is to inform the backend API that bearer of token is authorized to access backend and do actions there

So access token must be used as bearer token

> access tokens must never be used for authentication
> id tokens should not be used to gain access to an API
access token should be handled as an opaque string, if

**Comment by soxofaan** [comment]
from https://github.com/Open-EO/openeo-api/issues/201#issuecomment-527031784:
> The access_token is not necessarily a JWT and the back-en nees the information from the id_token

When playing around with tokens I also had impression that only id_token contains user information, but apparently the backend can also resolve an (possibly opaque) access token to user information using the `/userinfo` endpoint

**Comment by soxofaan** [comment]
Also, from my initial testing, it seems that only the access token contains the authorized scopes, which is necessary for the backend to support  #86

**Comment by aljacob** [comment]
I was also reading those different source on the web. To my understanding it is only problematic that the info that can possibly put on an access token is not standardized by now. I like the idea however, that the back-end can query this information from itself using something like /userinfo. That is what you intend right?
In the end I don't care, where I get the information on roles/scopes, as long as I get it in a verifiable and secure manner.
What are you using now to generate your tokens?
Ours are coming from the Microsoft azure frame-work. There we were able to configure that the scopes are included in the id token now, but I have not looked, into if this would be possible also with the access tokens there.

**Comment by soxofaan** [comment]
>  What are you using now to generate your tokens?
We are currenlty using Keycloak (https://www.keycloak.org/) which allows you to run your own identity provider with OAuth/OpenID Connect out of the box.

>  I like the idea however, that the back-end can query this information from itself using something like /userinfo. That is what you intend right?

Indeed. At the backend, I can do something like:

```python
headers = {
    "Authorization": "Bearer " + access_token
}
requests.get(base_url + '/userinfo', headers=headers).json() 
```
which gives me with our Keycloak setup something like this:
```
{'email': '<redacted>@<redacted>.vito.be',
 'email_verified': False,
 'family_name': 'EO',
 'given_name': 'Open EO',
 'name': 'Open EO EO',
 'preferred_username': 'openeo',
 'sub': 'f:LDAP-<redacted>:openeo'}
```

I'm also looking into how to get the associated scopes, which should be possible, but apparently it requires a bit more setup work.

**Comment by lforesta** [comment]
I like the idea of using the /userinfo endpoint
Maybe a small drawback is that this approach doubles the http requests, since each request to a protected endpoint at the backend result in a request to /userinfo on the identity provider, but this may be problematic only when the number of users on that backend starts to be very high I guess.

About the scopes, if one backend uses an external ip over which it has no control, it will not be able to set up custom scopes (e.g. for user roles), so this approach may not be standard between different backends.

**Comment by soxofaan** [comment]
> small drawback is that this approach doubles the http requests

a backend can easily workaround this with some caching (taking the lifetime of the access token into account).  The backend will probably need some kind of user management system anyway (mapping a OAuth provided email to a filesystem or OS-level user or something alike)

> will not be able to set up custom scopes

that is probably more a topic for  #86  and has less to do with the *how* to get the scopes associated with an access token

**Comment by m-mohr** [comment]
I think we are on the right track here. As far as I know, the workflow could/should be as follows:
1. Client requests OIDC info regarding supported Identity providers (IP) from openEO Driver at /credentials/oidc
2. User selects IP he wants to use
3. Client requests OIDC well-known document from the IP
4. OIDC workflow starts as requested by client and supported by IP
5. Client gets access token and refresh token.
6. Client sends access token to Driver.
7. Driver requests user info from IP with access token. Driver may cache the user info until the client sends a different access token.
8. Client may additionally also request user info from IP with access token.
9. Once access token expires, Client requests a new access token from IP by sending the refresh token.
10. Flow basically starts at 5 again.

Most of the steps can be handled by a certified OIDC library.

**Comment by soxofaan** [comment]
I have the same workflow in mind. Some remarks about the steps:

1/2 Note that this also has to work for batch/CLI contexts: e.g. script knows beforehand which IP to use. So you could say that (part of) 2. comes before 1. in a way.

6 "Client sends access token to Driver" might sound bit misleading:  the access token should not be sent standalone. For clarity I would say "Client makes API requests, using the access token as bearer token in HTTP Authorization header of each requests"


7 Driver should also invalidate cache when access token expires (Driver should be able to get expiry info from with IP)

8 should normally not be necessary in the context of OpenID Connect I think, as the id token should contain all user information for the Client.

**Comment by m-mohr** [comment]
> 1/2 Note that this also has to work for batch/CLI contexts: e.g. script knows beforehand which IP to use. So you could say that (part of) 2. comes before 1. in a way.

I don't get this. You need to know the available IPs before you can select one?! If you already know the IP (where from?) then you could probably simply skip 2.

> 6 "Client sends access token to Driver" might sound bit misleading:  the access token should not be sent standalone. For clarity I would say "Client makes API requests, using the access token as bearer token in HTTP Authorization header of each requests"

Indeed, that description was a bit too short. Updated above.

> 7 Driver should also invalidate cache when access token expires (Driver should be able to get expiry info from with IP)

Sounds good, but I'm not sure how the driver gets the expiry info?

> 8 should normally not be necessary in the context of OpenID Connect I think, as the id token should contain all user information for the Client.

Depends on the specified response_type.

**Comment by soxofaan** [comment]
>> 1/2 Note that this also has to work for batch/CLI contexts: e.g. script knows beforehand which IP to use. So you could say that (part of) 2. comes before 1. in a way.
>
> I don't get this. You need to know the available IPs before you can select one?! If you already know the IP (where from?) then you could probably simply skip 2.

Sorry, I probably didn't make myself clear. In case of CLI/batch jobs you probably do 1/2 separately from the other steps. For example, you manually use a web browser or online openEO editor/hub to find out the OIDC IP options of a given driver and then pick one. Then you write a python script where you hardcode the IP and use the python client to do steps 3 and further. So within the context of this python script, you know the IP "beforehand" (aka "hardcoded"). In this case, the client will probably still have to check this against the  `/credentials/oidc` info (e.g. to look up full IP urls). So you are still doing a bit of step 1 with the Python client too.

**Comment by m-mohr** [comment]
As also explained in PR #225, the access_token seems to be the way to go. AFAIK, back-ends can request claims using the Userinfo endpoint and get userinfo AND id_token as response. Therefore the client doesn't need to send the id_token to the back-end.

**Comment by m-mohr** [comment]
Another good article I found: https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis

**Comment by m-mohr** [comment]
Decision OIDC telco today:

* The client transfers the access_token to the back-end as discussed in this issue.
* To ensure we know from which identity provider this token comes from, we'll also transfer an provider id to the back-end (e.g. `basic//token` or `oidc/google/token`).
* The back-end can request user information from the /userinfo endpoint as specified in the OIDC spec. We checked so far that this works for VITO (keycloak) and EURAC (microsoft).

**Comment by m-mohr** [comment]
Closed with #225

**Comment by hayder1994ZH** [comment]
i'm send user info inside token what's a problem in this

**Comment by m-mohr** [comment]
The spec doesn't make any claims about this, it's up to the implementer.
