### ISSUE TITLE
Messages in error handling doc: mandatory or just examples

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#220]
In the error handling doc https://open-eo.github.io/openeo-api/errors/: 
the openEO error code table has an error message (a required field) for each error, but it is not clear from the doc whether these messages are to be followed verbatim or just example messages that can be finetuned (e.g. to contain more information).
I guess it's the latter, but the current doc suggest the former.

If so, I would suggest to change the column header in the tables to "Example Message"

**Comment by m-mohr** [comment]
Let's say it's a recommendation, but back-ends can send whatever message they like. ;-)

I'll consider it for the next version.

**Comment by m-mohr** [comment]
Fixed.
