### ISSUE TITLE
Callbacks: Allow using process_id directly in places where callback is expected

### ISSUE THREAD

**Issue by mkadunc** [Open-EO/openeo-api#244]
_Originally posted by @mkadunc in https://github.com/Open-EO/openeo-processes/issues/87#issuecomment-559448790_

Having callbacks with the same argument names as mathematical binary processes (x and y) will at some point allow us to simplify the specification of a callback to a simple pointer to a pre-defined process — e.g. the signature of the `or` process is `or(x:number, y:number)`, which is compatible with `overlap_resolver`, if it would be defined as `function(x:number, y:number)` - this allows specifying a graph that merges cubes as:

```JavaScript
{
    "process_id": "merge_cubes",
    "arguments": {
        "cube1": {"from_node": "linearscalerange3"},
        "cube2": {"from_node": "linearscalerange4"},
        "overlap_resolver": {"process_id": "or"}
    }
}
```

I'm not sure how well the possibility of having such callbacks is supported right now, but it should not be too difficult to implement support if we decide something like that would be valuable.

_Comment by @jdries in https://github.com/Open-EO/openeo-processes/issues/87#issuecomment-559456305_ :

> *(by @jdries)* Actually your second example process graph would be my preferred way of supporting it right now in the Python client and our backend. It is simpler, so reduces opportunities for misinterpretation. 
It's also the case that I'm not supporting more complex reducers right now for merge_cubes.

_Comment by @m-mohr in https://github.com/Open-EO/openeo-processes/issues/87#issuecomment-559464246_ :

> *(by @m-mohr)* re @mkadunc's side-note: The implicit mapping of parameters as proposed is currently not possible. I'm not sure whether it's really useful to solve this on the process graph level. I guess clients could simply do that for the user whenever parameters are "compatible" and come up with an "explicit" process graph. I think that would be the cleaner solution.

**Comment by m-mohr** [comment]
Moved to openeo-api as this is a process graph / API problem, not a processes issue.

The proposed behavior is only a shortcut for the case that only a single process is passed as callback, which assumes the process graph parameters and process parameters match. It would make the process graph schema more complex and the process graphs a bit smaller in some cases. So for now I think this is something that can be handled by the clients.

**Comment by soxofaan** [comment]
> So for now I think this is something that can be handled by the clients.

FYI: we do this in the Python client indeed.

e.g you can pass a simple string as reducer to `reduce_dimension`, which is converted to a real "child process graph". Very roughly it goes like this:
```python
# (DataCube class)
    def reduce_dimension(self, dimension: str, reducer: Union[PGNode, str]) -> 'DataCube':
        if isinstance(reducer, str):
            # Assume given reducer is a simple predefined reduce process_id
            reducer = PGNode(
                process_id=reducer, 
                arguments={"data": {"from_parameter": "data"}}
             )

        # use reduce PGNode to process futher ...
```

**Comment by m-mohr** [comment]
I'm closing this for now as that's not a high priority (user's usually don't even see this) and will be handled by clients most likely.
