### ISSUE TITLE
Error tagging

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#272]
Any reason `JobNotFound` is tagged with `Processes`?
https://github.com/Open-EO/openeo-api/blob/12471721d9c74262ae962f7ad6c746ac77aad382/errors.json#L256-L263

I'm also not sure it's necessary to put `FileNotFound` and `FileContentInvalid` under `Processes`
https://github.com/Open-EO/openeo-api/blob/12471721d9c74262ae962f7ad6c746ac77aad382/errors.json#L123-L130
https://github.com/Open-EO/openeo-api/blob/12471721d9c74262ae962f7ad6c746ac77aad382/errors.json#L173-L180

**Comment by m-mohr** [comment]
I realized the errors.json was quite outdated and the last major update was in 0.4 so took the chance to update it, see PR #275. It should incorporate the requested changes.
