### ISSUE TITLE
Clarify that back-ends without billing info are not always free

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#281]
Originated inhttps://github.com/Open-EO/openeo-hub/issues/68

The API spec says in /capabilities: 

> Billing related data [...] MUST be specified if the back-end uses any billing related functionalities

We should clarify that this doesn't mean the back-end is free to use. It should say that if you want to implement any billing related functions (e.g. /estimate or plan selection in /jobs) you need to specify the billing info. That doesn't mean you can't bill users at all. The API can be part of a broader payment model where individual API requests don't lead to individual costs, but be part of a "membership fee" model, for example. There you pay indirectly, let's say monthly 1000$ and can use the API with some limits, but without direct costs for requests. So API requests are not directly billed, but it's far from being free to use for all.

**Comment by christophfriedrich** [comment]
Thanks for the clarification.

> Providers may choose to
                      bill users outside of the API, e.g. with a monthly fee
                      that is giving them access a managed virtual machine 
                      running a protected API instance that is not billing based
                      on individual API interactions.

There's a "to" missing after "access".

And IMO the last three lines could be dropped altogether (unnecessary detail).

**Comment by m-mohr** [comment]
Good catch, I shortened to:

> e.g. with a monthly fee that is not depending on individual API interactions.

**Comment by christophfriedrich** [comment]
Elegant, I very much like your shortened version.
