### ISSUE TITLE
Duplicate versions in discovery

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#287]
An API issue to track the problem described in https://github.com/Open-EO/openeo-python-driver/issues/40

**Comment by christophfriedrich** [comment]
In the spec it says:

> MUST NOT be equal according to Semantic Versioning

In the changelog:

> must be unique

Can this be two different things? I.e. are there any two valid SemVer expressions that are considered equal under SemVer but are not identical letter-for-letter?

After doing a quick read at semver.org I think the answer to this question is "no", and if that's true, we could drop "according to Semantic Versioning" to remove unnecessary complexity.
