### ISSUE TITLE
Schema for user defined processes

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#293]
I'm not so familiar with json schema details, but there seems to be inconsistency about the `"process_graph"` key of `UserDefinedProcess` (as added in 1.0 of API):

https://github.com/Open-EO/openeo-api/blob/12471721d9c74262ae962f7ad6c746ac77aad382/openapi.yaml#L298-L308

it seems to be lacking here:
https://github.com/Open-EO/openeo-api/blob/12471721d9c74262ae962f7ad6c746ac77aad382/assets/pg-schema.json#L11-L25

**Comment by m-mohr** [comment]
If I'm not missing anything, it's here: https://github.com/Open-EO/openeo-api/blob/12471721d9c74262ae962f7ad6c746ac77aad382/assets/pg-schema.json#L117

**Comment by soxofaan** [comment]
ah, ok good to know

One minor follow up nitpick then: 
https://github.com/Open-EO/openeo-api/blob/12471721d9c74262ae962f7ad6c746ac77aad382/assets/pg-schema.json#L117-L128
change the title to "User defined process" to be more in line with the "Arguments" subsection of https://openeo.org/documentation/1.0/developers/api/reference.html#section/Processes/Process-Graphs ?

**Comment by m-mohr** [comment]
Somewhat true, although the schema is incomplete as it doesn't validate anything else than the process graph itself. It doesn't look for parameters and all the other properties a user-defined process may have. Adding that makes the schema much more complex and I'd have to maintain the schema in two places, but on the other hand it's incomplete. What are you using the schema for?

**Comment by soxofaan** [comment]
I'm not using it, I was just checking the specs related to user-defined processes and variable scoping (I'm working on VITO implementation around that).

**Comment by m-mohr** [comment]
Okay. Also, it says in the readme that "The assets folder contains some useful additional files such as examples or schemas. All of these are non-binding additions. The source of truth are the top-level specification files." So, I guess it's fine that it's incomplete regarding process metadata.
