### ISSUE TITLE
NoData handling in custom scripts

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-api#3]
Given that a user can provide his own scripts, how should he implement proper nodata handling?
The problem is that actual nodata values can differ, depending on the data layer and the endpoint against which the script is executed.
Options:

1. Nodata value is part of band metadata, developer should get it from there and propagate into his script
2. Nodata values passed along to the user function
3. Nodata 'macros' such as isNoData(x) are provided by the backend, that do the right thing?

This is linked to the question of what datatype will be used for pixel operations? We can standardize on always using doubles (even if the raw data is for instance stored as a byte), which would help in solving these things.

**Comment by gorelick** [comment]
Based on a lot of experience with Earth Engine, we concluded that it a nodata value directly in the data didn't make sense. Instead, we maintain a separate (1-byte) masking raster for each band.
Some of the many reasons we chose this:
1) Avoids potential exact comparison issues for non-integer bands (ie: floating point comparison issues, array-based or complex-typed pixels, etc).
2) Some data sources use multiple NODATA values (MODIS/MOD15A2).
3) No principled way to pick/propagate a single NODATA value when using heterogeneous inputs.
