### ISSUE TITLE
Authorization of /validation

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#314]
https://github.com/Open-EO/openeo-api/blob/12471721d9c74262ae962f7ad6c746ac77aad382/openapi.yaml#L2195-L2229

is it intended that `/validation`  can also be requested without authorization?

**Comment by m-mohr** [comment]
Yes, we thought it's helpful if users could validate and check whether the back-end is capable of running their stuff without registering and all the hassle.

**Comment by soxofaan** [comment]
ok make sense.

One minor thing is that `/validation` is currently only under category `User-Defined Processes` while from your reply I understand it is about validation of complete process graphs (as well). They are very much alike, but not completely: e.g. in a UDP it is fine to have unresolved parameters, while in a complete process graph you don't want that, which could be a relevant validation aspect.

**Comment by m-mohr** [comment]
Hmm, I now realized it's not clear from the description what to do with unresolved parameters. I'd argue that unresolved parameters shouldn't lead to an error (and thus it's in this category). Setting the parameters etc seems to me more fitting into submitting the batch job/service/... 

We should clarify that. If we wan't to check for unresolved parameters, I'd guess the best idea is adding a parameter to the request?

**Comment by soxofaan** [comment]
Well my question is also: if it's only about UDPs, is `/validation` the best url for that, as all the other UDP urls start with `/process_graphs`?

**Comment by m-mohr** [comment]
There are some things to consider:
1. The processes you send to batch jobs/services/... are still UDP techically. There's very little difference schema-wise (just in metadata).
2. /process_graphs/validation doesn't work due to the conflict with the id parameter
3. I'm not very happy with the legacy /process_graphs anymore anyway. It seems you are neither: #310
4. If we want to add validation including unresolved parameters, a simple backward compatible path parameter could be added.

So I think it's still reasonable to just call it /validation.

**Comment by soxofaan** [comment]
ok, so to conclude: the `/validation` endpoint is not only about UDPs in the sense of the named "user defined processes" with a life cycle (storage and retrieval), but also one-off "anonymous" process graphs (e.g. for batch jobs).
Shouldn't `/validation` then also be tagged under the generic tag "Data processing"?

I'm totally fine with adding parameters to `/validation` to fine-tune the validation mode/strategy. In VITO backend we haven't implemented it so far, so we don't have practical insights here.

**Comment by m-mohr** [comment]
Made the changes in PR #316
