### ISSUE TITLE
batch job logs when job is not finished or even started

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#315]
`GET /jobs/{job_id}/logs`

It's not specified explicitly how back-end should behave when a batch job is still "created"/"queued".
In VITO backend we currently throw `JobNotStarted` error, because that seemed fitting, but (D28) validator does not like that.
Should we just return empty list of log entries?

**Comment by m-mohr** [comment]
Logs can be used at all stages of a job, but I see that this part can be a bit misleading:

> If requested consecutively while a job is running, it is RECOMMENDED that clients use the offset parameter to get only the entries they have not received yet.

I'll try to improve and issue a PR.

**Comment by m-mohr** [comment]
see PR #316
