### ISSUE TITLE
No requirements for GET /service_types

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#318]
The service entries in `GET /service_types` currently have no required fields: each of `configuration`, `process_parameters` and `links` is allowed to be missing.

This caused the validator to accept the 0.4-style version of this endpoint in the 1.0-version of the VITO backend, e.g. currently at http://openeo.vgt.vito.be/openeo/1.0/service_types: 
```
{
    "WMTS": {
        "attributes": [],
        "parameters": {
            "colormap": {
                "default": "YlGn",
                "description": "The colormap to use.",
                "type": "a colormap to apply to single band layers"
            },
            "version": {
                "default": "1.0.0",
                "description": "The WMTS version to use.",
                "enum": [  "1.0.0"  ],
                "type": "string"
            }
        }
    }
}
```

Note these errors (that the validator didn't catch):
- 0.4-style fields `attributes` and `parameters`
- invalid `"type": "a colormap to apply to single band layers"`

Can this be avoided in some way?
For example require that `process_parameters` is present with at least and empty array?

**Comment by soxofaan** [comment]
cc @bgoesswe

**Comment by m-mohr** [comment]
Due to the "extensibility" of JSON, it's hard to avoid.

I'd actually like to require configuration and process_parameters as it hopefully makes the back-end think what it needs to set ;-) Not sure whether we should introduce the breaking change in the release week though.

It doesn't catch the invalid type as it's in an "undefined" structure, but it would be caught if it's in process_parameters.

**Comment by m-mohr** [comment]
What I guess would be useful to have in the validator, that it reports "undefined" properties as warnings or so. @bgoesswe

**Comment by soxofaan** [comment]
> Not sure whether we should introduce the breaking change in the release week though with just the reason to help the validator.

according to the openeo hub the support for secondary services is pretty thin (and so I assume practically unused), so I don't think a lot would break actually. But indeed it's already late to do these kind of things

**Comment by m-mohr** [comment]
Indeed, just VITO and GEE. I'm fine with it and if VITO is fine with it, too.

**Comment by bgoesswe** [comment]
> What I guess would be useful to have in the validator, that it reports "undefined" properties as warnings or so. @bgoesswe

Yep that seems like a good idea, I added a [new issue](https://github.com/Open-EO/openeo-backend-validator/issues/39) at the validator for that.

**Comment by soxofaan** [comment]
>  if VITO is fine with it

yes, it's not being used in a real application or use case at the moment, so we're open for minor breaking changes

**Comment by m-mohr** [comment]
See PR #322
