### ISSUE TITLE
Improve endpoint description consistency 

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#323]
While looking at the description of various endpoints in the API the last days I noticed there was difference in style.

For example,  I used a rudimentary script to extract the first sentence of the description of each endpoint and sorted them alphabetically:

Endpoint | First sentence of description
-------- | ------------
GET /conformance | A list of all conformance classes specified in OGC standards that the server conforms to 
POST /result | A user-defined process will be executed directly and the result will be downloaded in the format specified in the process graph 
POST /jobs/{job_id}/results | Adds a batch job to the processing queue to compute the results 
GET /jobs/{job_id}/results | After finishing processing this request will provide signed URLs to the processed files of the batch job with some additional metadata 
PATCH /services/{service_id} | Calling this endpoint will change the specified secondary web service but maintain its identifier 
POST /services | Calling this endpoint will create a secondary web service such as OGC WMShttpwww 
DELETE /services/{service_id} | Calling this endpoint will stop a given secondary web service to access result data 
DELETE /jobs/{job_id}/results | Cancels all related computations for this job at the back-end 
GET /jobs/{job_id}/estimate | Clients can ask for an estimate for a batch job 
POST /jobs | Creates a new batch processing task job from one or more chained processes at the back-end 
DELETE /jobs/{job_id} | Deletes all data related to this job 
DELETE /process_graphs/{process_graph_id} | Deletes the data related to this user-defined process including its process graph 
GET /collections/{collection_id} | Lists all information about a specific collection specified by the identifier collection_id 
GET /collections | Lists available collections with at least the required information 
PATCH /jobs/{job_id} | Modifies an existing job at the back-end but maintains the identifier 
GET /jobs | Requests to this endpoint will list all batch jobs submitted by a user 
GET /services | Requests to this endpoint will list all secondary web services submitted by a user 
GET /services/{service_id} | Requests to this endpoint will return JSON description of the secondary web service 
GET /jobs/{job_id} | Returns all information about a submitted batch job 
GET /process_graphs/{process_graph_id} | Returns all information about a user-defined process including its process graph 
GET / | Returns general information about the back-end including which version and endpoints of the openEO API are supported 
GET /udf_runtimes | Returns the supported runtimes for user-defined functions UDFs which includes either the programming languages including version numbers and available libraries including version numbers or docker containers 
GET /jobs/{job_id}/logs | Shows log entries for the batch job usually for debugging purposes 
GET /services/{service_id}/logs | Shows log entries for the secondary service usually for debugging purposes 
PUT /process_graphs/{process_graph_id} | Stores a provided user-defined process with process graph that can be reused in other processes 
GET /processes | The request asks the back-end for available predefined processes and returns detailed process descriptions including parameters and return values 
GET /file_formats | The request will ask the back-end for supported input and output file formats 
GET /service_types | The request will ask the back-end for supported secondary web service protocols such as OGC WMShttpwww 
GET /me | This endpoint always returns the user id and MAY return the disk quota available to the user 
GET /credentials/oidc | This endpoint lists the supported OpenID Connecthttpopenid 
GET /credentials/basic | This request checks the credentials provided through HTTP Basic Authentication according to RFC 7617httpstools 
DELETE /files/{path} | This service deletes an existing user-uploaded file specified by its path 
GET /files/{path} | This service downloads a user files identified by its path relative to the users root directory 
GET /process_graphs | This service lists all user-defined processes process graphs of the authenticated user that are stored at the back-end 
GET /files | This service lists all user-uploaded files that are stored at the back-end 
PUT /files/{path} | This service uploads a new or updates an existing file at a given path 
POST /validation | Validates a user-defined process without executing it 
GET /.well-known/openeo | Well-Known URI see RFC 5785httpstools 

Scanning through this list alphabetically you can find different styles:
- `A ... will be executed ... and the result will be downloaded ...`
- `Calling this endpoint will ....`
- `{verb} {noun}...`  (e.g. "adds a batch job", "Lists all information")
- `Requests to this endpoint will {verb} ...`
- `Returns {noun}`
- `Shows {noun}`  
- `The request asks the back-end for ...` / `The request will ask the back-end for ...`
- `This endpoint {verb} ...`
- `This request {verb} ...`
- `This service {verb} ...`
- `(...) this request will provide ...`

I think we can be a bit more consistent here.
There are probably guidelines about API doc writing out there we can follow.

**Comment by m-mohr** [comment]
The commit above applied some improvements, it's now usually (Lists/Modifies/Creates/Stores/Deletes/...) {resource}...
