### ISSUE TITLE
Logs: Add parameter for minimum severity

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#329]
It could be useful to filter logs returned to a client by a minimum severity. So for example, if I pass `severity=warning` to the back-end, it should only return warnings and errors, but not info or debug messages.

**Comment by soxofaan** [comment]
Do you mean filtering when _retrieving_ the logs? This would imply that the backend always has to keep track of all log levels, which might not be desirable for large jobs (debug level might be very verbose).

Alternative (or additional) approach: user has to specify minimum log level (e.g `warning` by default) when submitting the job

**Comment by m-mohr** [comment]
Yes, I was speaking about the retrieval. If the back-end doesn't provide some levels, that is fine. The contract doesn't enforce any level. Allowing the user to select what he wants to log when submitting the process is also a good idea.

**Comment by m-mohr** [comment]
This idea came up again in an internal discussion where @clausmichele proposed:

> > Could we add the info about each partial result in the log if a debug flag has been activated? [...]
