### ISSUE TITLE
Clarification of batch job result "geometry"

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#339]
Some notes/questions about the "geometry" field in a batch job result (`GET /jobs/{job_id}/results`):

- `geometry` is currently described  as 
    > Defines the full footprint of the asset

    Is "footprint" standard terminology? To me it sounds  a bit vague. I would interpret it as "bounding box", but there is already another field "bbox" for that, so my interpretation is probably wrong.
- At VITO we currently put the whole multi polygon geometry there in case of an aggregate_spatial query. We have some use cases handling geometries with over 100k fields, so that response can become quite large. Is that ok/intended? Or does a backend have the freedom to "simplify" a very large geometry to, say, just a bounding box?
- minor note: `GET /jobs/{job_id}/results` uses "geometry", while `aggregate_spatial` (and `filter_spatial`) use plural "geometries"

**Comment by m-mohr** [comment]
> * `geometry` is currently described  as
>   > Defines the full footprint of the asset

This originates from STAC: https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#item-fields

>   Is "footprint" standard terminology? To me it sounds  a bit vague. I would interpret it as "bounding box", but there is already another field "bbox" for that, so my interpretation is probably wrong.

I'm not sure whether that is standard terminology, but it feels like it is, e.g. http://resources.arcgis.com/en/help/main/10.1/index.html#//009t0000003v000000 
See also the image for the actual geometry you could provide. 


> * At VITO we currently put the whole multi polygon geometry there in case of an aggregate_spatial query. We have some use cases handling geometries with over 100k fields, so that response can become quite large. Is that ok/intended? Or does a backend have the freedom to "simplify" a very large geometry to, say, just a bounding box?

Yes, simplification is fine. STAC (and openEO) doesn't require any precision, also the bbox would be a valid simplification although it might mot always be very useful for users.

> * minor note: `GET /jobs/{job_id}/results` uses "geometry", while `aggregate_spatial` (and `filter_spatial`) use plural "geometries"

Yes, I'm aware of that. It seems more intuitive to use geometries in the processes (saying that it can be multiple), but geometry is what we inherit from GeoJSON.
