### ISSUE TITLE
If Time dimension of datacube has no timestamp but is an average of many years

### ISSUE THREAD

**Issue by prateekbudhwar** [Open-EO/openeo-api#340]
At Eurac we have a datacube that has a time dimension but its an average of 20 years of Data put as 1 year as monthly resolution, so its 12 months data with no real timestamps, Is there a way to tackle this situation when time dimension has no real timestamps, at the moment we have put this datacube time dimension as numbers from 1- 12 for 12 months,

**Comment by m-mohr** [comment]
In STAC you'd do that as Additional Dimension, not as Temporal (ISO8601) Dimension: https://github.com/radiantearth/stac-spec/tree/master/extensions/datacube#additional-dimension-object

For example:
```js
{
  type: "temporal",
  values: [1,2,3,4,5,6,7,8,9,10,11,12], // Can also be strings if you like
  unit: "month"
}
```
or with a step (works only for numerical dimension labels):
```js
{
  type: "temporal",
  extent: [1,12],
  step: 1,
  unit: "month"
}
```

**Comment by m-mohr** [comment]
See also https://github.com/radiantearth/stac-spec/pull/911, which makes a bit more clear how to handle the units field.

**Comment by m-mohr** [comment]
For the collection extent you could give the time frame that went into the average, i.e. the 20 years, e.g. 1980-01-01T00:00:00Z and 1999-12-31T23:59:59Z. Alternatively, but I think that is less favorable, you may also go with null and null.
