### ISSUE TITLE
Get pixel values easily

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#344]
It was noted that it is important to be able to interactively view/query values within arrays to enable user to perform checks on outputs for process verification without needing to dig into the files itself. This is useful for interactive evaluation of processes. As an example GEE was mentioned.
How can this be best addressed in the openEO API and Processes? Is the debug process enough? Would that need a separate endpoint? Or is it just a UI or client thing? (See also https://github.com/Open-EO/openeo-web-editor/issues/124)

**Comment by soxofaan** [comment]
I have been thinking about this too.

One possible solution: a new process, say `inspect`, that returns a JSON dump of the cube's metadata (dimension types/names/labels) and a small cutout of the data itself (e.g. a window of max 10 pixels in each dimension).
Something like this:

```
{
  "dimensions": [
    {"type": "spatial", "name": "x"},
    {"type": "bands", "labels": ["B02", "B03"], ....
    ....     
  },
  "data_sample": [
    [
      [3.2, 5.4, 9.3],
      [5.4, null, 3.2],
    ],
    [
      [6.5, 6.3, 6.7],
      .....
```

**Comment by m-mohr** [comment]
inspect sounds exactly like debug? :-) https://processes.openeo.org/#debug 
At least I had imagined something very similar...

Maybe debug is too general purpose though and we need a process with a more intuitive name and a strict STAC like response in JSON which clients can rely on? Debug doesn't require any specific format for the data as the data passed can be various types... Would you only be allowed to pass a data cube to inspect? How would you select the "pixel"?

**Comment by soxofaan** [comment]
> @soxofaan inspect sounds exactly like debug?

no not really: `debug` dumps to the logs and keeps the data as-is, while I mean a process that returns the JSON dump as `/result` response (so something like `save_result`, but always in JSON format and a limited window)

**Comment by m-mohr** [comment]
Yes, that behavior was intended. I think the example given was GEE and there it (print) is also just passing through and prints it in some kind of log window, while you can still get the full result. If inspect is just a shortcut for basically debug + save_result, redirecting the information from the limited window from logs to the output, why not just use filter_spatial and save_result as usual? It doesn't seem there's a big difference?

I think the use case was also meant differently in a way that you can just print intermediate info to the logs and then easily get results for pixels in the UI, too, without (re)processing again. Maybe I'm wrong though...

**Comment by soxofaan** [comment]
> Would you only be allowed to pass a data cube to inspect

No, it should handle every kind of result in a reasonable way (describe the metadata, and possibly small data sample). 


> How would you select the "pixel"?

That could be handled by additional process arguments. But I wonder if picking some exact pixel (region) is important here? The use case I had in mind is about quickly checking if the result has the dimensions I expect and value range I expect (e.g. is it a [0.0-1.0] value range, or integer [0, 255], or [-1000.0, 1000], etc ....?). Picking a particular pixel is not that important then. 
If I really want to inspect a particular pixel, I think I would prefer using a feature-rich GIS tool over manual JSON inspection.

but maybe I am misinterpreting the original use case/question.


As a side-note, I remember we still have some left-over endpoint `/timeseries/point?x=&y=` in the VITO backend to evaluate a process graph at a particular spatial position. But I don't know if that was a custom VITO endpoint or an old API experiment.

**Comment by m-mohr** [comment]
> No, it should handle every kind of result in a reasonable way (describe the metadata, and possibly small data sample).

Then it's really close to debug, but there's again the issue that you need to describe the "return value" depending on the input value. If you pass a number or list of numbers, it doesn't have dimensions for example.

> That could be handled by additional process arguments. But I wonder if picking some exact pixel (region) is important here? 

Not exactly sure. I think we need to figure out what use cases people have in mind exactly and only then we can make informed decisions about the processes or API improvements we need to make.

> If I really want to inspect a particular pixel, I think I would prefer using a feature-rich GIS tool over manual JSON inspection.

I think it was meant to be that you can do that with our clients, too. And that doesn't mean JSON inspection, but tools in the client libraries and web editor, that make it just work easily as in GEE for example.

> As a side-note, I remember we still have some left-over endpoint `/timeseries/point?x=&y=` in the VITO backend to evaluate a process graph at a particular spatial position. But I don't know if that was a custom VITO endpoint or an old API experiment.

That was never in the API and an experiment at VITO.

**Comment by mirt001** [comment]
Having an inspector is very important, but, in my opinion, it is not an openEO API issue. The feature can be entirely built on the client-side using existing openEO processes (filter_spatial). The decision of what should be implemented server-side and what should be implemented client-side usually depends on processing and data transfer requirements.

1. Client-side implementation of an inspector requires minimal processing
2. Client-side implementation of an inspector minimizes data-transfer

In GEE the inspector functionality is available only in the code-editor. It also doesn't seem to be a thin wrapper of a function in the javascript ee client library, which suggests it is built only because a visual, clickable environment exists.

In pure text environments, filter_spatial should be enough, in my opinion.

**Comment by m-mohr** [comment]
Doesn't seem to be in the scope of the openEO API itself. Refer to specific processes instead.
