### ISSUE TITLE
Schema of return value of  "callbacks"

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#350]
We have a couple of processes that take a "callback" (I know we deprecated that term, but using it avoids confusion here I think), e.g.:
- `reduce_dimension` has parameter "reducer": a callback that takes a `data` argument (type: array of any)
- `apply` has parameter "process": a callback that takes a `x` argument (type: any)
- `apply_neighborhood` has parameter "process": a callback that takes a `data` argument (type: rastercube)

Maybe this has been discussed before, but is there any reason we don't define the schema/type of what the callback should return?
For example:
- for reduce_dimension: `(array[any]) -> any`
- for apply: `(any) -> any`
- for apply_neighborhood: `(rastercube) -> rastercube`
- for count: `(any) -> bool`

**Comment by m-mohr** [comment]
This is a two-step change:

1.1.0: add `returns` as optional property (as a required property would be a breaking change)
2.0.0: make it required
