### ISSUE TITLE
Easier link to predefined schema subtypes

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#355]
https://github.com/Open-EO/openeo-api/blob/81dd248b9e8b8caeedbdd96c6a9dd8f3f56d0eb7/openapi.yaml#L263

provide direct deep link to https://github.com/Open-EO/openeo-processes/blob/master/meta/subtype-schemas.json  ?

**Comment by m-mohr** [comment]
I think I'd rather not rely too much on the internal structure of the repo.

**Comment by soxofaan** [comment]
ok fair enough. Maybe instead: add a couple of examples to make thinks a bit more concrete for the reader?
