### ISSUE TITLE
"parameters" keyword in parameter schemas?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#356]
https://github.com/Open-EO/openeo-api/blob/81dd248b9e8b8caeedbdd96c6a9dd8f3f56d0eb7/openapi.yaml#L244-L250

In the last line: what is this "parameters" keyword for? I'm afraid I don't understand the description. Do we have an example of this?

**Comment by m-mohr** [comment]
It is describing this extension to JSON Schema: https://github.com/Open-EO/openeo-processes/blob/master/reduce_dimension.json#L24-L45

**Comment by soxofaan** [comment]
ah ok, so it is specifically for the "process-graph" subtype?

**Comment by m-mohr** [comment]
Yes, although I'm not sure all JSON Schema tooling can actually make it depend on the value in the subtype (which is another new keyword).
