### ISSUE TITLE
Migrate to other CI than Travis

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#358]

**Comment by soxofaan** [comment]
Any particular reason or trigger to move away Travis, or just because of their declining support for open source repos?
For our openEO python repo's we are also considering to move away.
You already have an alternative in mind (e.g. github actions, or self hosted jenkins)?

**Comment by m-mohr** [comment]
See the related Teams discussion for more details

In short: It's that the CI now takes hours instead of minutes or even times out. If I push here I must be sure that the CI updates the API docs and doesn't leave them in outdated state for months because the CI timed out due to lack of resources.

I started to migrate several repos to GitHub Actions to test it and so far the experience was pretty good, so I'll continue to do so with the more complex configurations now (e.g. API and processes).
