### ISSUE TITLE
Unified Error Handling

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-api#36]
From a client perspective it would be great if all backends are sending error messages / exceptions in the same way in order to allow us to communicate those errors to the client.

I would suggest to use JSON as the message format and make use of the HTTP status code in the message and also in the response header. Maybe something like this for the response body:
```JSON
{
   "status": 400,
   "message": "Missing parameter: 'evaluate'"
}
```

**Comment by m-mohr** [comment]
Very good idea to send a message and strip down the number of error codes currently used, but what benefit does it have to repeat the status code in the response body again?

For i18n we might want to also return a individual error code for each message so that the clients can grab a suitable translation for the message?

**Comment by m-mohr** [comment]
First version is implemented with the linked commit. Additional error codes need to be specified over time...

**Comment by flahn** [comment]
Regarding the localization on errors, we should consider a proper content negotiation on the language, then. In the HTTP header there are options for "Accept-Language" and "Content-Language" for specifying the desired language output. It simplifies the error message and we get away with a leaner response that contains `message` instead of the whole language dump under `translation`.

This [link](http://apiux.com/2013/04/25/how-to-localize-your-api/) wraps up the issue nicely and hints to related standards.

**Comment by m-mohr** [comment]
Good idea.

Adding an optional "more information url" might be another nice thing to have.

**Comment by m-mohr** [comment]
Implemented.  More error codes need to be standardized though.
