### ISSUE TITLE
Broken RFC3339 links

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#361]
https://github.com/Open-EO/openeo-api/blob/81dd248b9e8b8caeedbdd96c6a9dd8f3f56d0eb7/openapi.yaml#L3527

these RFC3339 links (https://www.ietf.org/rfc/rfc3339) stopped working for me in Firefox (v85 on linux): instead of ascii text rendering I get a popup asking to download "application/octet-stream"

If I append `.txt` (https://www.ietf.org/rfc/rfc3339.txt), it works properly.

Google Chrome seems to render the URL without `.txt` properly.

**Comment by soxofaan** [comment]
from https://www.ietf.org/standards/rfcs/:

> To go directly to a text version of an RFC, type https://www.ietf.org/rfc/rfcNNNN.txt into the location field of your browser, where NNNN is the RFC number. 

So I guess we should  append the `.txt`

**Comment by m-mohr** [comment]
Could we also append .html? We have a couple of references to RFCs (I think) that are referring to chapters, which probably only works well in HTML mode?

**Comment by soxofaan** [comment]
according to https://www.ietf.org/standards/rfcs/, there is also rfc-editor.org :
> When in doubt, the RFC Editor site is the authoritative source page.

In case of rfc3330, it has this overview page: https://www.rfc-editor.org/info/rfc3339
linking to txt (https://www.rfc-editor.org/rfc/rfc3339.txt), html (https://www.rfc-editor.org/rfc/rfc3339.html) and pdf

**Comment by m-mohr** [comment]
Okay, I'll try to fix the issue.

**Comment by m-mohr** [comment]
Fixed, see commits above.

**Comment by soxofaan** [comment]
thanks

it seems however that you added double slashes after the domain, e.g.:

> https://www.rfc-editor.org//rfc/rfc3339.html#section-5.6

**Comment by m-mohr** [comment]
You are too fast! ;-) I've just force pushed a commit removing the `//` a minute later.
