### ISSUE TITLE
Job results properties: required or MAY?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#362]
https://github.com/Open-EO/openeo-api/blob/81dd248b9e8b8caeedbdd96c6a9dd8f3f56d0eb7/openapi.yaml#L3517-L3518

`GET /jobs/{}/results` response `properties` is required and there is a required `datetime` property in there,
but description says "MAY contain", which seems bit in conflict.

Maybe just drop the "MAY contain"?

**Comment by m-mohr** [comment]
This was meant to say, that additional properties in addition to the requirements are allowed to be added, e.g. you can add eo:cloud_cover or so to the properties.

**Comment by m-mohr** [comment]
I've made some changes to clarify the behavior, see the commit above. It's in the PR for STAC Collections as Job Results: #359
