### ISSUE TITLE
Better wording about case insensitive handling

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#371]
(from Open-EO/openeo-processes-python#22)

https://github.com/Open-EO/openeo-api/blob/81dd248b9e8b8caeedbdd96c6a9dd8f3f56d0eb7/openapi.yaml#L974

Wording is bit confusing (sound like backend can choose to be case insensitive or not).

Proposal:

> Format names MUST be handled case insensitively throughout the API.

Same applies to `Service names` and `Billing plans`

**Comment by m-mohr** [comment]
Just made a change, but my git is acting up and I can't commit yet. Will be available "soon".

**Comment by m-mohr** [comment]
> Format names MUST be accepted *case insensitive* throughout the API.

**Comment by m-mohr** [comment]
See PR #372
