### ISSUE TITLE
Recommend against versioning on minor level

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#393]
The API recommends versioning with major and minor version number, e.g. v1.0. in the URL.
As we are following semver this seems not ideal. Better would probably be to just use v1 for versioning.

**Comment by soxofaan** [comment]
Are you just talking about the backend URL? Or other version discovery/negotiation mechanisms as well?

In other word, do you mean 

> ... version number, e.g. v1.0. in the URL.

or 

> ... version number, e.g. v1.0., in the URL.

hashtag punctuation! :stuck_out_tongue:

**Comment by m-mohr** [comment]
Yeah, a typo. Just talking about the back-end URL. It's just a recommendation anyway, but I guess having a v1.1 and v1.0 instance usually doesn't make much sense. That's the only point here...

**Comment by m-mohr** [comment]
Actually, the description was already saying v1 (major path) should be used, but the default value was still v1.0. Fixed.
