### ISSUE TITLE
Handling of UDP process graph id

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#394]
conflict:

https://github.com/Open-EO/openeo-api/blob/f303d65a3291d4cd74dacc0e796803bb5d6fa03b/openapi.yaml#L2265-L2268

https://github.com/Open-EO/openeo-api/blob/f303d65a3291d4cd74dacc0e796803bb5d6fa03b/errors.json#L205-L211

**Comment by m-mohr** [comment]
Indeed. What's the better behavior? But I think the openapi.yaml is normative, errors.json is not, so the next step would probably to remove the ProcessGraphIdDoesntMatch error. It's probably also not mentioned anywhere?!

**Comment by m-mohr** [comment]
Removed.
