### ISSUE TITLE
"ProcessGraphMissing" error unclear when used with UDPs

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#395]
https://github.com/Open-EO/openeo-api/blob/f303d65a3291d4cd74dacc0e796803bb5d6fa03b/errors.json#L194-L203

"ProcessGraphMissing" is to be used with User-defined processes, but the description 

> The parameter `process` doesn't contain a valid process.

is unclear because there is no `process` parameter in the request

**Comment by m-mohr** [comment]
Clarified description a bit...
