### ISSUE TITLE
STAC example for collection has eo:gsd instead of gsd

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-api#399]
@m-mohr here https://openeo.org/documentation/1.0/developers/api/reference.html#section/STAC there is still `eo:gsd` as field instead of `gsd` only, as you mentioned here https://github.com/Open-EO/openeo-spring-driver/issues/35

**Comment by m-mohr** [comment]
True, that's an oversight on my side. Will fix the API document accordingly, but it will only propagate to openeo.org once we release a new version.

**Comment by m-mohr** [comment]
Fixed, thanks for reporting it.
