### ISSUE TITLE
Error code for invalid user/process/job Ids

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#402]
The API defines a couple of regexes for process/user/job ids: e.g. `^\w+$`, `^[\w\-\.~]+$`.
There is however no predefined error code to raise for violation of that constraint

**Comment by m-mohr** [comment]
Indeed, but the same is true also for other restrictions that are coming from the OpenAPI spec.
I usually only defined additional error messages when something was not directly specified through OpenAPI rules, but instead was in the written texts/descriptions. There are more things like what if a minimum or maximum constraint is violated? This could result in as many error codes as there are OpenAPI keywords. So I'm not sure we should actually get active here.

**Comment by soxofaan** [comment]
yes I understand, it was just a minor feature request. 

feel free to close as `wontfix`

**Comment by m-mohr** [comment]
Thanks for bringing it up. We may want to consider it again at some point, but it's not a priority right now.
