### ISSUE TITLE
capabilities billing default_plan

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#426]
https://github.com/Open-EO/openeo-api/blob/f303d65a3291d4cd74dacc0e796803bb5d6fa03b/openapi.yaml#L720-L726

first, a small typo:
> ... or has no default plan has been assigned  ...

While thinking about it, it seems this is not well defined yet:
Should the default plan be a paid or non-paid plan?
If it's a paid plan, then how can it be a default for free users?
If it's a non-paid plan, then it's not ideal to use as default for paying users (e.g.  they get worse performance because they are not using their paid plan).

**Comment by soxofaan** [comment]
(related to #425 )

**Comment by soxofaan** [comment]
given #425 :  maybe there should be no global default plan, and just a per user default plan (based on their subscription)?

**Comment by m-mohr** [comment]
I've tried to improve documentation in PR #428.

**Comment by jdries** [comment]
I'm also really not sure that we'll end up with a notion of multiple billing plans per user. 
There's also this vsc4 'plan', which is not really a billing plan but rather an entirely separate backend, which might even have specific capabilities.

**Comment by m-mohr** [comment]
Sure, but this is the general API so the option should be there anyway. Somewhat agree on vsc4. One the one hand it's a somewhat separate back-end, but on the other hand the billing plans were also meant to distinguish between different "configurations of hardware". So depends on a case by case basis.
