### ISSUE TITLE
STAC: reference_system in cube:dimensions oudated

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#435]
The definition of the cube:dimensions is outdated and was not properly updated to the recent version. We still allow EPSG code or PROJ string or WKT2, but instead of PROJ string it should be PROJJSON.

**Comment by christophfriedrich** [comment]
Currently PROJ string is listed as deprecated, what about PROJJSON?

**Comment by m-mohr** [comment]
PROJJSON is the successor of PROJ strings (at least in STAC and openEO).

**Comment by christophfriedrich** [comment]
So in openEO its use will be deprecated too? I.e. we would update something that is discouraged to be used anyway?!

**Comment by m-mohr** [comment]
The plan is to remove proj strings from the API spec and add projjson instead. It's simply updating to the current state in STAC as it was not updated properly in the release.

**Comment by m-mohr** [comment]
PROJ definitions (string) are still deprecated, PROJJSON was added.
