### ISSUE TITLE
FormatUnsuitable error missing

### ISSUE THREAD

**Issue by Ardweaden** [Open-EO/openeo-api#437]
I'm not sure if this was removed intentionally. `FormatUnsuitable` error was defined in 0.4.x version. It is raised by `save_result` process: https://docs.openeo.cloud/processes/#save_result

**Comment by soxofaan** [comment]
The error is now defined here (in openeo-processes project):
https://github.com/Open-EO/openeo-processes/blob/d0ce91fcd347360b907ea2d9589d7564a2c1e1e3/save_result.json#L49-L52

Note that errors.json in openeo-api project only defines errors that are relevant on the API level (e.g. related to authentication, batch jobs, ...). Errors that are process specific (such as FormatUnsuitable for save_result) are defined in the process specifications themselves

**Comment by Ardweaden** [comment]
That makes a lot of sense. Closing.
