### ISSUE TITLE
job results as STAC Collections

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#446]
https://github.com/Open-EO/openeo-api/blob/8467193c6a73c58017874e0625bb88fe6c080dfe/openapi.yaml#L3095-L3101

I'm confused about the `(1) is not compliant with previous versions of the openEO API.`. Shouldn't the reference be to `(2)` ,  which is the new collection approach, and consequently not compliant with previous versions of the openEO API?

**Comment by m-mohr** [comment]
No, (2) refers to a normal STAC catalog, i.e. deep hierarchy that doesn't usually have assets on the collection-level, but instead in assets in items somewhere in the hierarchy. So you can't simply check for "collection.assets" in the client code, but instead must crawl through the whole catalog to get all assets.

**Comment by soxofaan** [comment]
yes, I understand that, 
but then `(2)`  (no direct asset listing at `GET /jobs/{job_id}/results`) _is not_ compliant  with previous versions , 
while `(1)`  (has direct asset listing)   _is_ compliant  with previous versions.
Or am I misreading something?

**Comment by m-mohr** [comment]
Oh yeah, not sure where the (1) is coming from. It should be replaced with "it".

**Comment by m-mohr** [comment]
Fixed in https://github.com/Open-EO/openeo-api/commit/53a9c2da3925fe11af0d0b8a7cff55237ea94be0
