### ISSUE TITLE
references to `debug` process (now `inspect`)

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#448]
API still refers in a couple of places to `debug` process, which is renamed to `inspect` (https://github.com/Open-EO/openeo-processes/pull/310):

for example
https://github.com/Open-EO/openeo-api/blob/f303d65a3291d4cd74dacc0e796803bb5d6fa03b/openapi.yaml#L2680
https://github.com/Open-EO/openeo-api/blob/f303d65a3291d4cd74dacc0e796803bb5d6fa03b/openapi.yaml#L2972
https://github.com/Open-EO/openeo-api/blob/f303d65a3291d4cd74dacc0e796803bb5d6fa03b/openapi.yaml#L5515
https://github.com/Open-EO/openeo-api/blob/f303d65a3291d4cd74dacc0e796803bb5d6fa03b/openapi.yaml#L5867

**Comment by m-mohr** [comment]
You are looking at an old version. In draft branch these references are not present anymore / updated.

**Comment by soxofaan** [comment]
ok good

I noticed it on https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Batch-Jobs/operation/debug-job actually

you probably mentioned it somewhere, but do we have a draft-build of that page somewhere publicly? And if so, and can it be listed in that version picker on these pages? I often have that problem where I spot an issue, but it's a bit tedious to figure out if it is already addressed in draft.

**Comment by m-mohr** [comment]
openeo.org is always fixed on the latest released version. It's not completely straightforward to have draft on openeo.org, but could be a good idea for the future. maybe open an issue on openeo.org?

The latest draft is at https://api.openeo.org/draft (all the links to all versions are actually in the repo readme: https://github.com/Open-EO/openeo-api#versions--branches)

The comparison of changes via GitHub: https://github.com/Open-EO/openeo-api/compare/master...draft

**Comment by soxofaan** [comment]
> The latest draft is at https://api.openeo.org/draft (all the links to all versions are actually in the repo readme: https://github.com/Open-EO/openeo-api#versions--branches)


Oh great, I didn't notice that table "below the fold" :smile: . 
I should switch to these API docs at api.openeo.org links instead of the  one that is linked from openeo.org home page
