### ISSUE TITLE
No schema for process graphs?

### ISSUE THREAD

**Issue by LukeWeidenwalker** [Open-EO/openeo-api#452]
While working on process graph parsing recently I realized that the process-graph as an object doesn't actually have a complete schema in the API spec. Now I have a couple of questions!

- Are there plans for this to become part of the spec at some point?
- If not, how can I know what a valid process graph (e.g. as produced by one of the clients) will be structured like?
- I know of https://github.com/Open-EO/openeo-api/blob/master/assets/pg-schema.json, but the README of that repo says:
`The [assets](https://github.com/Open-EO/openeo-api/blob/master/assets) folder contains some useful additional files such as examples or schemas. All of these are non-binding additions. The source of truth are the top-level specification files.` Would you recommend for this schema to be used in backends? Is this actually still up-to-date with what clients produce currently?

Thanks a lot for any clarifications!

**Comment by m-mohr** [comment]
There's a complete OpenAPI schema in the API spec and additionally, there's the conversion to JSON Schema for only the process graph. 

The OpenAPI one is the source of truth and complete. With (good) OpenAPI validators you should be able to check process graphs. If you have better access to JSON schema validators, you can at least validate the graph portion using that.

I'm not 100% sure how to help here?

**Comment by LukeWeidenwalker** [comment]
Sorry, I will try to clarify what I'm after:
- https://github.com/Open-EO/openeo-processes/blob/master/meta/subtype-schemas.json#L250  defines the `process-graph` subtype, but this subtype only tells me that an object with subtype `process-graph` has a `process_graph` object, which in turn has the `process_id` and `arguments` fields. 
- Is there any schema for the process arguments? I know this depends on which process it is, but there are common fields like `from_parameter` and `from_node`? Are these schematised anywhere? I guess I expected the schema to include a `process_node` type, that wraps the actual process definition to make fields like `from_parameter` parsable even if the actual process definition hasn't been loaded yet. 
- Does this make sense? Sorry if I'm being unclear, I'm still learning the spec - happy to jump on a call sometime if that would help!

**Comment by LukeWeidenwalker** [comment]
Sorry, I just realized that this whole question was based on a misunderstanding on my part and doesn't really make sense - will close!
