### ISSUE TITLE
clarification of job_id uniqueness

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#454]
https://github.com/Open-EO/openeo-api/blob/f303d65a3291d4cd74dacc0e796803bb5d6fa03b/openapi.yaml#L5267-L5271

small question: the uniqueness of a batch job id, is that per user or  for the back-end as a whole?

This aspect might become important once sharing across users becomes a topic

**Comment by m-mohr** [comment]
For the sharing aspect, it was meant to be per back-end. I'll go through the API document later and check all uniqueness constraints and clarify the scope.
