### ISSUE TITLE
Type definitions for custom backend response types

### ISSUE THREAD

**Issue by GreatEmerald** [Open-EO/openeo-api#46]
Backends are able to return specific, custom-defined types as JSON objects, for instance for time series (a JSON dictionary with dates and values of the time series at a particular pixel). However, there is not enough information in the response to tell what type of response it is, so clients cannot tell how to parse the response into something that is immediately usable for the users. The [Python client example](https://github.com/Open-EO/openeo-python-client/blob/master/examples/notebooks/Compositing.ipynb) currently just has the user parse the result from raw JSON, which is not very user-friendly.

**Comment by m-mohr** [comment]
@GreatEmerald Do you have a concrete suggestion for this? I can't really come up with a reasonable and satisfying solution.

This probably relates to how we solve #72.

**Comment by m-mohr** [comment]
This also relates to and might be solved with #47 as it also includes schema definitions for process results.

**Comment by m-mohr** [comment]
This will be solved with #47.

* If your last process is returning images (most of them) or vector data, you'll retrieve them using any of the supported image output formats (GTiff, PNG, JPEG, etc.) or vector output formats (GeoJSON, KML, Shapefiles, etc.). 
* If your last process is returning anything else (usually structured data as JSON), it will be defined in the process specification and can be parsed accordingly. Therefore we need a JSON (or RAW?) output format. 

If the back-end is not able to transform the data to the requested data format, an error with openEO error code 3004 should be thrown.
