### ISSUE TITLE
Clarify the user-defined processes

### ISSUE THREAD

**Issue by flahn** [Open-EO/openeo-api#464]
There is the following definition for user-defined process in section Processes / Process Graphs / User-defined process:

> A user-defined process in a process graph is a child process graph, to be evaluated as part of another process.

In my opinion this definition is to narrow and just captures the old term "Callback". As I understood user-defined processes are all user-defined process graphs, but in this case a user-defined process is used as a reducer / apply function. I don't know how to call those functions in openEO. Can we call it Lambda expression? 

In any case, it should be more clear that a user-defined process is not only a child process, but every user-defined process graph.

**Comment by m-mohr** [comment]
I've rewritten the section in 835bb65a1292808e2158346afa3773f36f736a2a
