### ISSUE TITLE
`GET /jobs/{job_id}/results` summary

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#482]
https://github.com/Open-EO/openeo-api/blob/16b1122c7090cc4fedcabace48686a4f73c1c876/openapi.yaml#L2995-L2999

I'm always confused by the summary of `GET /jobs/{job_id}/results`: it says "download results", but it's just about _listing_ metadata about the job result and related assets. The assets include a download link, but that link and the actual downloading are not part of the openEO API.

I'd propose to change the summary to

> List batch job result metadata and assets

**Comment by m-mohr** [comment]
Fixed
