### ISSUE TITLE
minimum log_level for `GET /../logs`

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#485]
#431 added option to specify minimum log_level at job submission time. 
We are currently also playing with setting a minimum log_level when requesting the logs (e.g. `GET /jobs/{job_id}/logs)`. 
For example see Open-EO/openeo-python-client#332, where we filter client side to only show error logs, but we've experienced that it would be better to do the filtering already back-end side (for performance reasons).

Can we add an optional `log_level` parameter to `GET /jobs/{job_id}/logs` and `GET /services/{service_id}/logs`  for back-end side log filtering at retrieval time?

refs and related issues
- #329 
- #431
- Open-EO/openeo-python-client#332

**Comment by m-mohr** [comment]
I guess we can do that, but I'm wondering whether it should be a user-selectable list instead, e.g. if a user uses inspect with the debug level and only wants the debug level + maybe errors.

**Comment by soxofaan** [comment]
> I guess we can do that, but I'm wondering whether it should be a user-selectable list instead,

For back-end side filtering I would just go for a minimum level, which is the most natural way of working with logs. 
If some additional filtering is necessary: that can always be done client side (e.g. interactively), but I would not extend that UI aspect to the back-end side.

**Comment by clausmichele** [comment]
For the use case that @soxofaan mentioned it seems reasonable to have a flag/parameter to set the level. Other than that, I agree with @m-mohr that if I user asks specifically for the logs the default value should be the lowest possible, so that they can filter them later at the client side.
