### ISSUE TITLE
Better example (openeo) domains

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#489]
spin off from #487 : instead of using `https://example.openeo.org` as example domain: use `https://openeo.example` which is more explicit about being a non-functional example (`.example` is dedicated TLD for this).

**Comment by soxofaan** [comment]
did a quick extraction of all domains in openeo.yaml (draft branch) and found these candidates to be addressed, cleaned up (or at least be given a look)
```
  35 example.openeo.org
  10 www.cool-cloud-corp.com
   7 example.com
   5 cool-eo-cloud-corp.com
   3 openeo.cloudprovider.com
   3 cool-cloud-corp.com
   2 client.org
   2 localhost
   1 provider.com
   1 www.example.com
```
(number is count of occurrences)

**Comment by m-mohr** [comment]
Thanks.

Maybe also replace the v1.0 with v1.
