### ISSUE TITLE
Naming convention inside summaries field of collections isn't compliant with STAC Specification

### ISSUE THREAD

**Issue by GeraldIr** [Open-EO/openeo-api#493]
https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md says that summaries can contain either an array of any value or a range which is a dictionary of a minimum and a maximum.

The naming convention here differs in the openEO API spec as "min" and "max" are used instead of "minimum" and "maximum".

Should be an easy fix as you just need to rename the 'min' and 'max' in the 'collection_summary_stats' in the specification file (line 4190 in the json, 4450 in the yaml), examples should also be adjusted.

**Comment by m-mohr** [comment]
It was actually only the examples that were not updated, this will be fixed in the next release.
