### ISSUE TITLE
Add `links` to /jobs/{job_id}

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#495]

**Comment by soxofaan** [comment]
maybe I'm misunderstanding, but I already see a links property for `GET /jobs/{job_id}`  at https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Batch-Jobs/operation/describe-job (defined by components/schemas/batch_job I guess)

**Comment by m-mohr** [comment]
lol, thanks
