### ISSUE TITLE
Remove openeo:status from the "/jobs/{job_id}/results" collection response

### ISSUE THREAD

**Issue by rtmiz** [Open-EO/openeo-api#497]
This field seems a bit redundant, as the value is gotten from a seperate API call to /jobs/{job_id} (which delivers metadata for a specific batch job), also it's only needed if the response is a STAC collection AND partial is true.

What is this actually being used for? It's not a huge inconvenience to update from 1.1.0 to 1.2.0 but it seems a bit strange.

I guess clarification would be nice.

**Comment by m-mohr** [comment]
It is an optional field (for now), so you can omit it if you want. The use case is that it can be important to know whether the job is complete (i.e. status = finished) or incomplete (i.e. status = canceled/error) in the metadata.

Related:
- https://github.com/Open-EO/openeo-api/pull/433#discussion_r765767152
- https://github.com/Open-EO/openeo-api/issues/374

**Comment by jdries** [comment]
we actually use this field now to enable federated processing, so please don't remove it.

**Comment by m-mohr** [comment]
Yes, it was just recently added and is optional. So you don't need to implement it and there are good reasons in several use cases to keep it.
