### ISSUE TITLE
Generic linking to endpoint docs

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#501]
While tinkering with the docs for Python client, I was wondering if there is a generic way to construct a link to API documentation from a given endpoint, e.g. `GET /jobs/{job_id}`.
The deep link to the corresponding docs are now (for example) `https://api.openeo.org/#tag/Batch-Jobs/operation/describe-job`, but I can not automatically derive that URL fragment from just `GET /jobs/{job_id}`.

Is it possible to support predictable deeplinks/fragments, e.g. `#GET_jobs_job_id`?
Or is it possible to trigger the search functionality from a certain URL pattern to end up on the correct section of the docs?

**Comment by m-mohr** [comment]
Not possible as far as I'm aware, but you'd need to ask the redoc devs for a definitive answer :-)

**Comment by soxofaan** [comment]
ok, probably not something that is going to happen soon. Going to close this minor thing then
