### ISSUE TITLE
ProcessGraphComplexity: too heavy instead of too complex

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#527]
https://github.com/Open-EO/openeo-api/blob/c5a45b4647b06e313a4f099e9119bfa3cca5c6a3/errors.json#L243-L245

Can we generalize the "... is too complex for synchronous ..." in message and description to a more generic "... is too heavy for ..." (or something alike) ?

Usually the complexity of the process graph is not really a problem, but just a spatial or temporal extent that is too large for sync processing.

For me it's fine to keep the error code.

(I'd make a PR directly for that, but that would conflict with #526)

**Comment by m-mohr** [comment]
#526 has been merged, feel free to create new one for this issue. Thanks.
