### ISSUE TITLE
Download authorization

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#53]
The GET /jobs/.../download request responds with a list of URLs.
These can be protected 
1. using API authorization strategy, i.e. you need to send the Authorization header, which prevents them to be downloaded by browsers as they usually don't send Authorization headers with GET requests,
2. be freely available,
3. or protected with another access key in the URL (signed URLs), e.g. `http://someCDN.com/api/{CDN_ACCESS_TOKEN}/{job_id}`.

We need to specify somewhere, whether the Authorization header needs to be sent or not.

**Comment by m-mohr** [comment]
> How long are the download links valid for? Is it something that each backend decides?
That's probably the case, yes. 

Personally, I'd suggest to implement 3 as it's the best compromise between security and ease of use. It would support your use case. They could expire after an hour or so, maybe that's even something that should be returned in the header, e.g.  `Expires: Wed, 21 Oct 2018 07:28:00 GMT`

**Comment by GreatEmerald** [comment]
Hm, then how is 3 different from 2? You still get told the URL in both cases, right? The only difference I can see is that in 3 it's guaranteed to expire at some point? But then the backends would probably not want to keep the data after the download links expire, either.

**Comment by m-mohr** [comment]
Depending on the URL schema of the back-end others might easily guess the URL generated from 2 and download your files. 
3 would generate a personalized expiring token and include it in the URL as "password". So the only difference is whether the data is protected or not, nothing more. Clients can actually also just decide what they want to support. Technically there is no difference (for the clients) indeed.

**Comment by GreatEmerald** [comment]
Ah, I see. So far, though, the job IDs seem to be generated randomly on all the backends, and downloads are usually tied to the job ID, so 2 is still not guessable. But that may depend on the backend...

I also wonder how much of an issue it is that others may be able to download your products; it's all just spatial data generated from public datasets. Though I guess in the future there may be backends with non-public datasets...

**Comment by m-mohr** [comment]
The job_id might be used to share stuff, too. Some back-ends also might not generate uuids that are hard to guess, but simply increment an ID, which can be guessed easily.

**Comment by m-mohr** [comment]
We use suggestion 3 (signed URLS) for now. Added descriptions to the spec.
