### ISSUE TITLE
Constraints for band names?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-api#530]
We recently had some issues related to band names. E.g. a user that (accidentally) (re)named bands to something like
```
"Band(name='NDVI', common_name=None, wavelength_um=None, aliases=None, gsd=None)"
```
so band name is full of parenthesis, equal signs, spaces, etc.

We were wondering if there any constraints for band names  in the openEO spec or STAC specs? 
I couldn't really find any so far, so does that mean that all kinds of "special" characters, whitespace, newlines, unicode/emoji stuff is allowed in band names?

**Comment by soxofaan** [comment]
cc @JeroenVerstraelen  @EmileSonneveld

**Comment by m-mohr** [comment]
Band names (and all other dimension labels), are unrestricted, indeed. Both in openEO and STAC.
The example looks more like a client issue to me though?

**Comment by soxofaan** [comment]
ok thanks for confirming

> The example looks more like a client issue to me though?

More like a accidental user error, nothing much the client could have done. (Unless there were band name constraints the client could enforce)
