### ISSUE TITLE
License for UDP?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#531]
A license field for user-defined processes might be a good idea.

**Comment by soxofaan** [comment]
How do you envision this information to be consumed? 
Just as a visualization thing or should clients/backends check licences against allow-lists in some way?

**Comment by m-mohr** [comment]
Just for consumption, i.e. if you wish to publish your algorithm somewhere...
Came up in alignment discussions with OGC API - Processes, which have such a field.

**Comment by soxofaan** [comment]
Other related metadata fields that could be considered or might be relevant to the discussion: author and version (as discussed earlier in https://github.com/Open-EO/openeo-api/issues/480 )

This is not meant as scope-creep for this ticket, but it could help to to decide if you want to put all this kind of metadata at the object top level, or group things under a more generic "metadata" field (e.g. to isolate free-form metadata from more standardized properties)

**Comment by m-mohr** [comment]
Agreed, maybe we can take over these fields from STAC.

**Comment by soxofaan** [comment]
Another thing to consider here is a changelog (or link to one)

**Comment by m-mohr** [comment]
I just realized we already have a solution for license and changelog in the links:

```json
{
  "rel": "version-history",
  "href": "http://openeo.example/changelog.txt",
  "type": "text/plain",
  "title": "Changelog"
}
```

and 

```json
{
  "rel": "license",
  "href": "http://openeo.example/license.txt",
  "type": "text/plain",
  "title": "License: CC-BY-4.0"
}
```

**Comment by m-mohr** [comment]
See PR #536  for a clarification in the spec.
