### ISSUE TITLE
Sentinel 1 data have wrong coordinates

### ISSUE THREAD

**Issue by AlessandroGrassi1998** [Open-EO/openeo-api#537]
For my research I need pair of Sentinel 1 and Sentinel 2 images of the same ROI. While Sentinel 2 data is correct, Sentinel 1 seems to always have a shift to the left (east) even if coordinates are completely matching with Sentinel 2 data. An example can be seen in the attatched files.
Here is the code I use to download:
```
spatial_extent = {
      "west": x_start,
      "south": y_start,
      "east": x_end,
      "north": y_end}
datacube = connection.load_collection(
      "SENTINEL1_GRD",
      spatial_extent=spatial_extent,
      temporal_extent = [sample_day, sample_day],
      bands=["VV", "VH"],
  ).sar_backscatter(coefficient="beta0")
if os.path.exists(s1_save_path):
      os.remove(s1_save_path)
datacube.download(s1_save_path, format=format)

datacube = connection.load_collection(
      "SENTINEL2_L2A",
      spatial_extent=spatial_extent,
      temporal_extent = [sample_day, sample_day],
      bands=["B04", "B08", "B11", "SCL"],
      max_cloud_cover=2
  )
if os.path.exists(s2_save_path):
      os.
remove(s2_save_path)
datacube.download(s2_save_path, format=format)
```

Here is the tif file I have downloaded: 
[sentinel_files.zip](https://github.com/user-attachments/files/15899510/sentinel_files.zip)

![image](https://github.com/Open-EO/openeo-api/assets/41692959/a540d73b-9bad-44e5-95ec-d6d56f5c4935)
![image](https://github.com/Open-EO/openeo-api/assets/41692959/ca25a6b7-0e2f-481b-ad4a-499061f8d077)

**Comment by m-mohr** [comment]
Please reach out to the support channels of the provider you are using. This repository is about the API specification.
