### ISSUE TITLE
Underscores in paths are invisible in the rendered docs

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-api#546]
In the heading for each endpoint, if the path includes an underscore, it appears like a space:

> ![grafik](https://github.com/user-attachments/assets/bd3f9003-98d6-4319-9f1f-5641953385ce)

The problem is the CSS rule `overflow-x: hidden` on the immediately surrounding `<span>` element. I don't know if this can be fixed here or is an upstream issue?

Firefox 131.0.2 (64-bit) on Windows 11

**Comment by christophfriedrich** [comment]
The screenshot above was taken with the Snipping Tool of Windows. Interestingly, when I take it with the tool that is built into Firefox, the underscore IS visible in the saved image, despite it not showing on screen:

> ![grafik](https://github.com/user-attachments/assets/453f2227-e169-44ce-b27b-15ab0206e4b9)

Also, I realised that `overflow-x` shouldn't do anything here at all, as the underscore is in the `y` direction... Maybe it's actually a Firefox bug.

**Comment by christophfriedrich** [comment]
I reported this over at Bugzilla because the behaviour feels super weird to me: https://bugzilla.mozilla.org/show_bug.cgi?id=1925957

**Comment by m-mohr** [comment]
Thanks for the report. Yeah, that's either a bug in Redoc or in the browser, indeed.
Not sure we can do anything about it.

**Comment by soxofaan** [comment]
for what it's worth: looks fine for me

(Firefox 131.03 and Chromium 129.0.6668.100 on Linux (Ubuntu 22.04))

![image](https://github.com/user-attachments/assets/5715d601-3890-40e6-804e-7bd0fa1581b5)

**Comment by m-mohr** [comment]
Might be a font issue (different sizes?).

I think we can close here and wait for upstream changes.
