### ISSUE TITLE
Backend compliance test suite

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-api#78]
To formalize our API spec, a black-box test suite for backends is needed. This has already been discussed during the sprints, but apparently did not yet exist as an issue.
This relates to other issues that try to formalize the API. 

It might be needed to also provide a small dataset, that should be exposed by the backend that want to do a validation. This will allow the test to also compare the actual output of algorithms.

**Comment by m-mohr** [comment]
Yes, this is definitely needed and I'd schedule implementation right after API spec v0.3 as the API spec v0.0.2 is not formalized enough to be really testable.

We need to think about tooling for both the JSON responses and for the processed EO data itself.
JSON responses can probably tested relatively easy with tools such as https://assertible.com/ Unfortunately, it is not open-source and I couldn't find anything that is open-source and supports OpenAPI 3.0. Their free plan might be too limiting. For EO data validation we may need a custom implementation.

**Comment by m-mohr** [comment]
Edzer asked on the mailing list:
> Is anyone aware of existing reference test datasets that have been used and published for EO processing purposes?

Response from Noel:
> I can think of a number of datasets that people test with, but in general the source data changes often enough that I don't know of anyone that's maintaining "reference" versions.  For instance, the USGS developed a set of images for use in the ACCA and FMASK cloud masking experiments, but that dataset hasn't been updated to keep up with Collection 1 activities.  Same with e.g.: MODIS Landcover.
> 
> But we treat a number of datasets as "canonical" as they're fairly ubiquitous and are freely available with permissive licenses:
> Elevation - USGS/SRTMGL1_V003
> Landcover - MODIS/MCD12Q1
> Crop Type - USGS/NLCD
> Nighttime lights - NOAA/DMSP-OLS/CALIBRATED_LIGHTS_V4
> High res optical - USDA/NAIP
> International Borders - USDOS/LSIB (GAUL is the standard, but not permissive).

**Comment by christophfriedrich** [comment]
I signed up for assertible.com and had a look at it. It offers quite a wide range of assertion types and the free plan does allow a fair amount of tests. They offer the possibility to import from a Swagger/OpenAPI (v2 or v3) definition (among others, like a Postman collection or "API Blueprint").

So I had a try importing our [`swagger.json`](https://github.com/Open-EO/openeo-api/blob/master/swagger.json) into their system. The import worked, but didn't consider all the available information. For example, for `GET /capabilities/output_formats` the import created only one assertion: whether it returns `200 OK`. And that despite the fact that the `swagger.json` [contains a schema definition](https://github.com/Open-EO/openeo-api/blob/master/swagger.json#L661) for the answer expected from that endpoint.

Assertible.com therefore doesn't look like THE tool that could automatically turn our OpenAPI definition into a testing suite. Manual conversion of the schemas would be necessary. If that's done, the service could be quite powerful.

**Comment by neteler** [comment]
My colleague Marc Jansen (https://github.com/marcjansen) suggests to look at https://www.soapui.org

**Comment by christophfriedrich** [comment]
Thanks for the idea @neteler. I installed it and my impression isn't positive. I wasn't able to find an import option for Swagger, which immediately makes this suite a worse choice than Assertible. There's supposed to be a plugin that adds Swagger import, but it [appears to be broken](https://github.com/SmartBear/readyapi-swagger-plugin/issues/51) and [unsupported](https://github.com/SmartBear/readyapi-swagger-plugin/issues/60).

Also, looking at [their releases section](https://github.com/SmartBear/soapui/releases), SoapUI seems to be a stale project in general. I couldn't find hints on whether it even supports OpenAPI v3, and therefore doubt it does.

To me it appears that while the SoapUI software (or the Ready API suite, of which it is a part) is still sold (the SoapUI pro version is ca. 600 euros per year), SmartBear's focus now lies on Swagger Editor and Swagger UI etc. as indicated e.g. by [this blogpost](https://blog.smartbear.com/software-quality/openapi-3-0-how-to-design-and-document-apis-with-the-latest-openapi-specification-on-demand-training/), which mentions these two tools but not "the old ones" - I guess they're not being developed anymore.

Further input is highly appreciated!

**Comment by neteler** [comment]
... ok, we didn't check SoapUI in detail. Will keep eyes open!

**Comment by m-mohr** [comment]
During EODC Forum it was also asked by users to bring this forward with regards to comparability of results.

**Comment by m-mohr** [comment]
That's interesting: https://github.com/opengeospatial/WFS_FES/issues/129
It may allow us to just specify JSON schemas for our API in the API spec and then use JSON schema validators for validation, which is not yet a thing for OpenAPI schemas.
