### ISSUE TITLE
Authorization Scopes

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-api#86]
OpenID Connect (and OAuth) as implemented with #74 allow to add authorization scopes to limit access of users. We should think about the scopes we support and pre-define, e.g.
* read:services
* write:services
* read:jobs
* write:jobs
* ...

**Comment by m-mohr** [comment]
Related to #201

**Comment by m-mohr** [comment]
Another thing we probably need to consider is that the back-end needs to tell the client which scopes to ask permission for. The client probably doesn't really know what to ask for.

See also https://developer.okta.com/blog/2017/07/25/oidc-primer-part-1#whats-a-scope

**Comment by soxofaan** [comment]
> the back-end needs to tell the client which scopes to ask permission for. 

Do we already have indication that predefined scopes won't be enough?

**Comment by m-mohr** [comment]
@soxofaan Clients need to specify scopes to ask permission for. As different back-ends may need different permissions, I think it would just make the API more flexible to allow specifying additional scopes.

**Comment by soxofaan** [comment]
I understand, but I'm just wondering if it is already nececarry to worry about custom scopes if we haven't listed predefined scopes yet

Or inversely, is it necessary to worry about predefined scopes if a backend would able to define custom scopes anyway.

At the moment, I would think it's enough to just have predefined scopes and no custom ones.

**Comment by m-mohr** [comment]
@soxofaan I think at Google (for the GEE driver) I'd need to set a Earth Engine scope or so, but I still need to check that. In the end, it's just a field that a back-end may return for each OIDC Provider, which lists (additional?) scopes a client should request. I'm just talking about a field for communication, I'm not speaking yet about any pre-defined scopes (that was the original intent of the issue, but maybe it's enough to have this field for communication).

**Comment by soxofaan** [comment]
> In the end, it's just a field that a back-end may return for each OIDC Provider, which lists (additional?) scopes a client should request. 

I think scopes are tied to the backend (the "resource server" in OAuth speak), regardless of the OIDC provider, so it shouldn't be a list per provider

**Comment by m-mohr** [comment]
@soxofaan I dont' think so: https://auth0.com/docs/scopes/current/oidc-scopes
If I set the EarthEngine scope for example, I'd like to know from the OpenID Provider, whether I have the permissions to use EE or not. I don't think this is tied to the back-end. The back-end is more another relying party (client) to the OP.

**Comment by m-mohr** [comment]
Closed with #225
